export type ProviderStatus='PENDING'|'VERIFIED'|'SUSPENDED'
export type AdminOverview={totalUsers:number;customers:number;providers:number;pendingProviders:number;verifiedProviders:number;suspendedProviders:number;totalOrders:number;completedOrders:number;activeOrders:number;totalOrderValueMinor:number;aiRequestsThisMonth:number}
export type AdminUser={id:string;firstName:string;lastName:string;email:string;role:'CUSTOMER'|'PROVIDER'|'ADMIN';subscriptionPlan:'FREE'|'PRO'|'BUSINESS';providerStatus:ProviderStatus;createdAt:string;providerProfile:{displayName:string}|null;_count:{orders:number;aiUsage:number}}
export type AdminProvider={id:string;email:string;firstName:string;lastName:string;providerStatus:ProviderStatus;createdAt:string;providerProfile:{slug:string;displayName:string;headline:string|null;description:string|null;category:string|null;website:string|null;location:string|null;languages:string[];updatedAt:string}|null;_count:{assignedOrders:number}}
export type AdminOrder={id:string;orderNumber:string;serviceTitleKa:string;serviceTitleEn:string;providerName:string;packageNameKa:string;packageNameEn:string;priceMinor:number;currency:string;status:string;paymentStatus:string;createdAt:string;customer:{firstName:string;lastName:string;email:string}}
export type AdminSubscription={id:string;firstName:string;lastName:string;email:string;subscriptionPlan:'FREE'|'PRO'|'BUSINESS';updatedAt:string}
export type AdminPage<T>={total:number;page:number;pageSize:number}&T
export type AdminUsage={id:string;feature:string;periodKey:string;requestCount:number;limit:number;updatedAt:string;user:{id:string;firstName:string;lastName:string;email:string;subscriptionPlan:'FREE'|'PRO'|'BUSINESS'}}
export class AdminApiError extends Error{constructor(public code:string){super(code)}}
async function request<T>(path:string,options?:RequestInit):Promise<T>{let response:Response;try{response=await fetch(path,{...options,credentials:'include',headers:{'Content-Type':'application/json',...options?.headers}})}catch{throw new AdminApiError('NETWORK_ERROR')}const body=await response.json().catch(()=>null) as {data?:T;error?:{code?:string}}|null;if(!response.ok||!body?.data)throw new AdminApiError(body?.error?.code??'INTERNAL_ERROR');return body.data}
const query=(values:Record<string,string|undefined>)=>{const params=new URLSearchParams();Object.entries(values).forEach(([key,value])=>value&&params.set(key,value));return params.toString()}
export const adminApi={overview:()=>request<AdminOverview>('/api/admin/overview'),users:(filters:Record<string,string|undefined>)=>request<AdminPage<{users:AdminUser[]}>>(`/api/admin/users?${query(filters)}`),providers:(filters:Record<string,string|undefined>)=>request<AdminPage<{providers:AdminProvider[]}>>(`/api/admin/providers?${query(filters)}`),providerAction:(id:string,action:'VERIFY'|'SUSPEND'|'REINSTATE')=>request<{provider:{id:string;providerStatus:ProviderStatus}}>(`/api/admin/providers/${encodeURIComponent(id)}/status`,{method:'PATCH',body:JSON.stringify({action})}),orders:(filters:Record<string,string|undefined>)=>request<AdminPage<{orders:AdminOrder[]}>>(`/api/admin/orders?${query(filters)}`),subscriptions:(filters:Record<string,string|undefined>)=>request<AdminPage<{subscriptions:AdminSubscription[];distribution:{subscriptionPlan:string;_count:number}[]}>>(`/api/admin/subscriptions?${query(filters)}`),usage:(filters:Record<string,string|undefined>)=>request<AdminPage<{usage:AdminUsage[]}>>(`/api/admin/ai-usage?${query(filters)}`)}
