import express, { Router, type Request } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { requireAdmin, requireAuth } from '../middleware/auth.js'
import { getUsageLimit, type SubscriptionPlan, type UsageMetric } from '../../shared/subscriptions.js'
import { createNotification } from '../lib/notifications.js'
import { orderCatalog } from '../../shared/orderCatalog.js'
import { destroyServiceAsset, uploadServiceAsset } from '../lib/cloudinary.js'
import { resolveEffectivePlan, subscriptionUserSelect } from '../billing/subscriptionService.js'

export const adminRouter = Router()
adminRouter.use(requireAuth, requireAdmin)

const pageSchema = z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), search: z.string().trim().max(100).default('') })
const providerActionSchema = z.object({ action: z.enum(['VERIFY', 'SUSPEND', 'REINSTATE']) }).strict()
const userProfileSchema=z.object({firstName:z.string().trim().min(1).max(80),lastName:z.string().trim().min(1).max(80),phone:z.string().trim().max(30).nullable()}).strict()
const roleSchema=z.object({role:z.enum(['CUSTOMER','PROVIDER','ADMIN'])}).strict()
const planSchema=z.object({plan:z.enum(['FREE','PRO','BUSINESS'])}).strict()
const providerProfileSchema=z.object({displayName:z.string().trim().min(1).max(120),headline:z.string().trim().max(160).nullable(),description:z.string().trim().max(4000).nullable(),category:z.string().trim().max(100).nullable(),website:z.string().trim().url().max(500).nullable(),location:z.string().trim().max(160).nullable(),languages:z.array(z.string().trim().min(1).max(50)).max(20),slug:z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(80)}).strict()
const orderStatusSchema=z.object({status:z.enum(['PENDING','CONFIRMED','IN_PROGRESS','IN_REVIEW','COMPLETED','CANCELLED'])}).strict()
const packageSchema=z.object({nameKa:z.string().trim().min(1).max(100),nameEn:z.string().trim().min(1).max(100),descriptionKa:z.string().trim().max(1000).optional(),descriptionEn:z.string().trim().max(1000).optional(),priceMinor:z.number().int().min(0).max(100_000_000),deliveryDays:z.number().int().min(1).max(365),featuresKa:z.array(z.string().trim().min(1).max(200)).max(30),featuresEn:z.array(z.string().trim().min(1).max(200)).max(30)}).strict()
const serviceSchema=z.object({titleKa:z.string().trim().min(1).max(160),titleEn:z.string().trim().min(1).max(160),descriptionKa:z.string().trim().min(1).max(4000),descriptionEn:z.string().trim().min(1).max(4000),category:z.string().trim().regex(/^[a-z0-9-]+$/).max(80),priceMinor:z.number().int().min(0).max(100_000_000),deliveryDays:z.number().int().min(1).max(365),status:z.enum(['ACTIVE','ARCHIVED']),packages:z.array(packageSchema).max(3).optional()}).strict()
const catalogIds=new Set(['social-management','business-website','seo-audit','brand-identity','ad-campaign','promo-video','process-automation','ai-content','content-strategy','email-marketing','landing-page','ecommerce-ui','instagram-content','tiktok-plan','local-seo','google-ads','logo-animation','crm-automation','ai-chat-workflow','growth-consulting'])
const digitalStepIds=new Set(['seo-audit','process-automation','local-seo','ai-chat-workflow'])
const bulkIdsSchema=z.object({serviceIds:z.array(z.string().trim().min(1).max(120)).min(1).max(100)}).strict()
const bulkStatusSchema=bulkIdsSchema.extend({status:z.enum(['ACTIVE','ARCHIVED'])}).strict()
const createServiceSchema=serviceSchema.extend({slug:z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(100),source:z.literal('DIGITAL_STEP')}).strict()
const audit=(request:Request,action:string,resourceType:string,resourceId:string,changedFields:string[])=>console.info('admin_mutation',{adminUserId:request.auth?.userId,action,resourceType,resourceId,changedFields})
const featureMetric: Record<string, UsageMetric> = { AI_ASSISTANT:'AI_REQUESTS', POST_GENERATOR:'POST_GENERATIONS', CONTENT_IDEAS:'CONTENT_IDEA_GENERATIONS', MARKETING_PLANNER:'MARKETING_PLAN_GENERATIONS', BUSINESS_ANALYSIS:'BUSINESS_ANALYSIS_GENERATIONS' }

adminRouter.get('/overview', async (_request, response, next) => {
  try {
    const periodKey = new Date().toISOString().slice(0, 7)
    const [totalUsers, customers, providers, pendingProviders, verifiedProviders, suspendedProviders, totalOrders, completedOrders, activeOrders, orderValue, ai] = await Promise.all([
      prisma.user.count(), prisma.user.count({where:{role:'CUSTOMER'}}), prisma.user.count({where:{role:'PROVIDER'}}), prisma.user.count({where:{role:'PROVIDER',providerStatus:'PENDING'}}), prisma.user.count({where:{role:'PROVIDER',providerStatus:'VERIFIED'}}), prisma.user.count({where:{role:'PROVIDER',providerStatus:'SUSPENDED'}}), prisma.order.count(), prisma.order.count({where:{status:'COMPLETED'}}), prisma.order.count({where:{status:{in:['PENDING','CONFIRMED','IN_PROGRESS','IN_REVIEW']}}}), prisma.order.aggregate({_sum:{priceMinor:true}}), prisma.aIUsage.aggregate({where:{periodKey},_sum:{requestCount:true}}),
    ])
    response.json({data:{totalUsers,customers,providers,pendingProviders,verifiedProviders,suspendedProviders,totalOrders,completedOrders,activeOrders,totalOrderValueMinor:orderValue._sum.priceMinor??0,aiRequestsThisMonth:ai._sum.requestCount??0}})
  } catch (error) { next(error) }
})

adminRouter.get('/users', async (request, response, next) => {
  const parsed=pageSchema.extend({role:z.enum(['CUSTOMER','PROVIDER','ADMIN']).optional(),plan:z.enum(['FREE','PRO','BUSINESS']).optional()}).safeParse(request.query)
  if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}})
  try {
    const {page,pageSize,search,role,plan}=parsed.data
    const where={...(role&&{role}),...(search&&{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}}]})}
    const select={id:true,firstName:true,lastName:true,phone:true,email:true,emailVerifiedAt:true,role:true,providerStatus:true,createdAt:true,providerProfile:{select:{displayName:true}},_count:{select:{orders:true,aiUsage:true}},...subscriptionUserSelect} as const
    // Effective plan is derived from override/subscription state, so a plan filter
    // cannot safely target the legacy subscriptionPlan column.
    if(plan){
      const resolved=(await prisma.user.findMany({where,select,orderBy:{createdAt:'desc'}})).map(user=>({...user,subscriptionPlan:resolveEffectivePlan(user).plan})).filter(user=>user.subscriptionPlan===plan)
      return response.json({data:{users:resolved.slice((page-1)*pageSize,page*pageSize),total:resolved.length,page,pageSize}})
    }
    const [rows,total]=await Promise.all([prisma.user.findMany({where,select,orderBy:{createdAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.user.count({where})])
    return response.json({data:{users:rows.map(user=>({...user,subscriptionPlan:resolveEffectivePlan(user).plan})),total,page,pageSize}})
  } catch(error){next(error)}
})

adminRouter.patch('/users/:id/profile',async(request,response,next)=>{const parsed=userProfileSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION',issues:parsed.error.issues}});try{const user=await prisma.user.update({where:{id:request.params.id},data:parsed.data,select:{id:true,firstName:true,lastName:true,phone:true,updatedAt:true}});audit(request,'UPDATE_PROFILE','USER',user.id,Object.keys(parsed.data));response.json({data:{user}})}catch(error){next(error)}})
adminRouter.patch('/users/:id/plan',async(request,response,next)=>{const parsed=planSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const user=await prisma.user.update({where:{id:request.params.id},data:{manualPlanOverride:parsed.data.plan,manualPlanOverrideExpiresAt:null},select:{id:true,manualPlanOverride:true,updatedAt:true}});audit(request,'OVERRIDE_PLAN','USER',user.id,['manualPlanOverride']);response.json({data:{user:{...user,subscriptionPlan:user.manualPlanOverride!}}})}catch(error){next(error)}})
adminRouter.patch('/users/:id/role',async(request,response,next)=>{const parsed=roleSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const current=await prisma.user.findUnique({where:{id:request.params.id},select:{id:true,role:true}});if(!current)return response.status(404).json({error:{code:'USER_NOT_FOUND'}});if(current.id===request.auth?.userId&&parsed.data.role!=='ADMIN')return response.status(409).json({error:{code:'SELF_DEMOTION_FORBIDDEN'}});if(current.role==='ADMIN'&&parsed.data.role!=='ADMIN'&&await prisma.user.count({where:{role:'ADMIN'}})<=1)return response.status(409).json({error:{code:'LAST_ADMIN'}});const user=await prisma.user.update({where:{id:current.id},data:{role:parsed.data.role},select:{id:true,role:true,updatedAt:true}});audit(request,'CHANGE_ROLE','USER',user.id,['role']);response.json({data:{user}})}catch(error){next(error)}})

adminRouter.get('/providers', async (request,response,next)=>{const parsed=pageSchema.extend({status:z.enum(['PENDING','VERIFIED','SUSPENDED']).optional()}).safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search,status}=parsed.data;const where={role:'PROVIDER' as const,...(status&&{providerStatus:status}),...(search&&{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}},{providerProfile:{displayName:{contains:search,mode:'insensitive' as const}}}]})};const[providers,total]=await Promise.all([prisma.user.findMany({where,select:{id:true,email:true,firstName:true,lastName:true,providerStatus:true,createdAt:true,providerProfile:{select:{slug:true,displayName:true,headline:true,description:true,category:true,website:true,location:true,languages:true,updatedAt:true}},_count:{select:{assignedOrders:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.user.count({where})]);response.json({data:{providers,total,page,pageSize}})}catch(error){next(error)}})

adminRouter.patch('/providers/:id/status', async(request,response,next)=>{const parsed=providerActionSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const provider=await prisma.user.findFirst({where:{id:request.params.id,role:'PROVIDER'},select:{id:true,providerStatus:true}});if(!provider)return response.status(404).json({error:{code:'PROVIDER_NOT_FOUND'}});const transitions={VERIFY:{from:['PENDING'],to:'VERIFIED'},SUSPEND:{from:['VERIFIED'],to:'SUSPENDED'},REINSTATE:{from:['SUSPENDED'],to:'VERIFIED'}} as const;const transition=transitions[parsed.data.action];if(!(transition.from as readonly string[]).includes(provider.providerStatus))return response.status(409).json({error:{code:'INVALID_PROVIDER_STATUS'}});const updated=await prisma.user.update({where:{id:provider.id},data:{providerStatus:transition.to},select:{id:true,providerStatus:true,updatedAt:true}});await createNotification({userId:provider.id,type:transition.to==='VERIFIED'?'PROVIDER_VERIFIED':'PROVIDER_SUSPENDED'});audit(request,'CHANGE_STATUS','PROVIDER',provider.id,['providerStatus']);response.json({data:{provider:updated}})}catch(error){next(error)}})

adminRouter.patch('/providers/:id/profile',async(request,response,next)=>{const parsed=providerProfileSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION',issues:parsed.error.issues}});try{const owner=await prisma.user.findFirst({where:{id:request.params.id,role:'PROVIDER'},select:{id:true}});if(!owner)return response.status(404).json({error:{code:'PROVIDER_NOT_FOUND'}});const profile=await prisma.providerProfile.update({where:{userId:owner.id},data:parsed.data,select:{slug:true,displayName:true,headline:true,description:true,category:true,website:true,location:true,languages:true,updatedAt:true}});await prisma.user.update({where:{id:owner.id},data:{providerSlug:parsed.data.slug}});audit(request,'UPDATE_PROFILE','PROVIDER',owner.id,Object.keys(parsed.data));response.json({data:{profile}})}catch(error){next(error)}})

adminRouter.get('/orders',async(request,response,next)=>{const parsed=pageSchema.extend({status:z.enum(['PENDING','CONFIRMED','IN_PROGRESS','IN_REVIEW','COMPLETED','CANCELLED']).optional()}).safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search,status}=parsed.data;const where={...(status&&{status}),...(search&&{OR:[{orderNumber:{contains:search,mode:'insensitive' as const}},{serviceTitleEn:{contains:search,mode:'insensitive' as const}},{serviceTitleKa:{contains:search,mode:'insensitive' as const}},{providerName:{contains:search,mode:'insensitive' as const}},{customer:{email:{contains:search,mode:'insensitive' as const}}}]})};const[orders,total]=await Promise.all([prisma.order.findMany({where,select:{id:true,orderNumber:true,serviceTitleKa:true,serviceTitleEn:true,providerName:true,packageNameKa:true,packageNameEn:true,priceMinor:true,currency:true,status:true,paymentStatus:true,createdAt:true,customer:{select:{firstName:true,lastName:true,email:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.order.count({where})]);response.json({data:{orders,total,page,pageSize}})}catch(error){next(error)}})

adminRouter.patch('/orders/:id/status',async(request,response,next)=>{const parsed=orderStatusSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const current=await prisma.order.findUnique({where:{id:request.params.id},select:{id:true,status:true,customerId:true,providerUserId:true}});if(!current)return response.status(404).json({error:{code:'ORDER_NOT_FOUND'}});const order=await prisma.order.update({where:{id:current.id},data:{status:parsed.data.status},select:{id:true,status:true,updatedAt:true}});const notificationType=({CONFIRMED:'ORDER_CONFIRMED',IN_PROGRESS:'ORDER_IN_PROGRESS',IN_REVIEW:'ORDER_IN_REVIEW',COMPLETED:'ORDER_COMPLETED',CANCELLED:'ORDER_CANCELLED'} as Record<string,string>)[parsed.data.status] as 'ORDER_CONFIRMED'|'ORDER_IN_PROGRESS'|'ORDER_IN_REVIEW'|'ORDER_COMPLETED'|'ORDER_CANCELLED'|undefined;const recipients=[current.customerId,current.providerUserId].filter((id):id is string=>Boolean(id));if(notificationType)await Promise.all(recipients.map(userId=>createNotification({userId,type:notificationType,data:{orderId:current.id}})));audit(request,'OVERRIDE_STATUS','ORDER',order.id,['status']);response.json({data:{order}})}catch(error){next(error)}})

adminRouter.get('/service-overrides',async(_request,response,next)=>{try{response.json({data:{overrides:await prisma.catalogServiceOverride.findMany({include:{media:{orderBy:{sortOrder:'asc'}}},orderBy:{updatedAt:'desc'}})}})}catch(error){next(error)}})
adminRouter.post('/services',async(request,response,next)=>{const parsed=createServiceSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION',issues:parsed.error.issues}});try{const{source,...data}=parsed.data;const serviceId=`official-${data.slug}`;const slugInCode=orderCatalog.some(service=>service.slug===data.slug);const existing=await prisma.catalogServiceOverride.findFirst({where:{OR:[{serviceId},{slug:data.slug}]},select:{serviceId:true}});if(slugInCode||existing)return response.status(409).json({error:{code:'SERVICE_ALREADY_EXISTS'}});const service=await prisma.catalogServiceOverride.create({data:{serviceId,...data,isCustom:true,serviceSource:source,updatedByUserId:request.auth!.userId}});audit(request,'CREATE_OFFICIAL_SERVICE','SERVICE',service.serviceId,['serviceSource',...Object.keys(data)]);response.status(201).json({data:{service}})}catch(error){next(error)}})
adminRouter.patch('/services/:id',async(request,response,next)=>{const parsed=serviceSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION',issues:parsed.error.issues}});try{const existing=await prisma.catalogServiceOverride.findUnique({where:{serviceId:request.params.id},select:{isCustom:true}});if(!existing&&!catalogIds.has(request.params.id))return response.status(404).json({error:{code:'SERVICE_NOT_FOUND'}});const service=await prisma.catalogServiceOverride.upsert({where:{serviceId:request.params.id},create:{serviceId:request.params.id,...parsed.data,serviceSource:digitalStepIds.has(request.params.id)?'DIGITAL_STEP':'VERIFIED_PROVIDER',updatedByUserId:request.auth!.userId},update:{...parsed.data,statusOnly:false,updatedByUserId:request.auth!.userId}});audit(request,'UPDATE_CATALOG_SERVICE','SERVICE',service.serviceId,Object.keys(parsed.data));response.json({data:{service}})}catch(error){next(error)}})

const mediaBody=express.raw({type:['image/jpeg','image/png','image/webp','image/avif','video/mp4','video/webm','video/quicktime'],limit:'100mb'})
const mediaType=(bytes:Buffer,mime:string):'IMAGE'|'VIDEO'|null=>{const hex=bytes.subarray(0,16).toString('hex'),ascii=bytes.subarray(0,16).toString('ascii');if(mime==='image/jpeg'&&hex.startsWith('ffd8ff'))return'IMAGE';if(mime==='image/png'&&hex.startsWith('89504e470d0a1a0a'))return'IMAGE';if(mime==='image/webp'&&ascii.startsWith('RIFF')&&ascii.slice(8,12)==='WEBP')return'IMAGE';if(mime==='image/avif'&&ascii.slice(4,12).includes('ftyp'))return'IMAGE';if(['video/mp4','video/quicktime'].includes(mime)&&ascii.slice(4,12).includes('ftyp'))return'VIDEO';if(mime==='video/webm'&&hex.startsWith('1a45dfa3'))return'VIDEO';return null}
adminRouter.post('/services/:id/media',mediaBody,async(request,response,next)=>{try{const service=await prisma.catalogServiceOverride.findUnique({where:{serviceId:request.params.id},select:{serviceId:true,serviceSource:true,_count:{select:{media:true}},media:{select:{type:true}}}});if(!service)return response.status(404).json({error:{code:'SERVICE_NOT_FOUND'}});const bytes=Buffer.isBuffer(request.body)?request.body:Buffer.alloc(0),mime=request.headers['content-type']?.split(';')[0]??'',type=mediaType(bytes,mime);if(!type)return response.status(415).json({error:{code:'UNSUPPORTED_MEDIA_TYPE'}});const limit=type==='IMAGE'?10*1024*1024:100*1024*1024,count=service.media.filter(item=>item.type===type).length,max=type==='IMAGE'?10:3;if(!bytes.length||bytes.length>limit)return response.status(413).json({error:{code:'MEDIA_TOO_LARGE'}});if(count>=max)return response.status(409).json({error:{code:'MEDIA_COUNT_LIMIT'}});const asset=await uploadServiceAsset(bytes,service.serviceId,type==='IMAGE'?'image':'video');try{const media=await prisma.serviceMedia.create({data:{serviceId:service.serviceId,type,url:asset.secure_url,publicId:asset.public_id,width:asset.width,height:asset.height,duration:asset.duration,sortOrder:service._count.media}});audit(request,'UPLOAD_SERVICE_MEDIA','SERVICE',service.serviceId,['media']);return response.status(201).json({data:{media}})}catch(error){await destroyServiceAsset(asset.public_id,type==='IMAGE'?'image':'video').catch(()=>undefined);throw error}}catch(error){next(error)}})
adminRouter.delete('/services/:serviceId/media/:mediaId',async(request,response,next)=>{try{const media=await prisma.serviceMedia.findFirst({where:{id:request.params.mediaId,serviceId:request.params.serviceId},include:{service:{select:{serviceSource:true}}}});if(!media)return response.status(404).json({error:{code:'SERVICE_MEDIA_NOT_FOUND'}});await destroyServiceAsset(media.publicId,media.type==='IMAGE'?'image':'video');await prisma.serviceMedia.delete({where:{id:media.id}});audit(request,'DELETE_SERVICE_MEDIA','SERVICE',media.serviceId,['media']);response.json({data:{deleted:true}})}catch(error){next(error)}})

type BulkItem={serviceId:string;outcome:'UPDATED'|'DELETED'|'ARCHIVED_INSTEAD'|'SKIPPED'|'FAILED';reason?:string}
const bulkResponse=(requested:string[],results:BulkItem[])=>({requested:requested.length,succeeded:results.filter(x=>['UPDATED','DELETED','ARCHIVED_INSTEAD'].includes(x.outcome)).length,skipped:results.filter(x=>x.outcome==='SKIPPED').length,failed:results.filter(x=>x.outcome==='FAILED').length,results})
const knownServices=async(ids:string[])=>{const records=await prisma.catalogServiceOverride.findMany({where:{serviceId:{in:ids}}});return new Map(records.map(x=>[x.serviceId,x]))}
adminRouter.post('/services/bulk-status',async(request,response,next)=>{const parsed=bulkStatusSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION',issues:parsed.error.issues}});const ids=[...new Set(parsed.data.serviceIds)];try{const records=await knownServices(ids);const results:BulkItem[]=[];for(const id of ids){const current=records.get(id);if(!current&&!catalogIds.has(id)){results.push({serviceId:id,outcome:'FAILED',reason:'SERVICE_NOT_FOUND'});continue}if((current?.status??'ACTIVE')===parsed.data.status){results.push({serviceId:id,outcome:'SKIPPED',reason:'ALREADY_IN_STATUS'});continue}await prisma.catalogServiceOverride.upsert({where:{serviceId:id},create:{serviceId:id,titleKa:id,titleEn:id,descriptionKa:id,descriptionEn:id,category:'uncategorized',priceMinor:0,deliveryDays:1,status:parsed.data.status,statusOnly:true,serviceSource:digitalStepIds.has(id)?'DIGITAL_STEP':'VERIFIED_PROVIDER',updatedByUserId:request.auth!.userId},update:{status:parsed.data.status,updatedByUserId:request.auth!.userId}});results.push({serviceId:id,outcome:'UPDATED'})}audit(request,'BULK_STATUS','SERVICE',ids.join(','),['status']);response.json({data:bulkResponse(ids,results)})}catch(error){next(error)}})
adminRouter.post('/services/bulk-archive',async(request,response,next)=>{const parsed=bulkIdsSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION',issues:parsed.error.issues}});const ids=[...new Set(parsed.data.serviceIds)];try{const records=await knownServices(ids);const results:BulkItem[]=[];for(const id of ids){const current=records.get(id);if(!current&&!catalogIds.has(id)){results.push({serviceId:id,outcome:'FAILED',reason:'SERVICE_NOT_FOUND'});continue}if(current?.status==='ARCHIVED'){results.push({serviceId:id,outcome:'SKIPPED',reason:'ALREADY_IN_STATUS'});continue}await prisma.catalogServiceOverride.upsert({where:{serviceId:id},create:{serviceId:id,titleKa:id,titleEn:id,descriptionKa:id,descriptionEn:id,category:'uncategorized',priceMinor:0,deliveryDays:1,status:'ARCHIVED',statusOnly:true,serviceSource:digitalStepIds.has(id)?'DIGITAL_STEP':'VERIFIED_PROVIDER',updatedByUserId:request.auth!.userId},update:{status:'ARCHIVED',updatedByUserId:request.auth!.userId}});results.push({serviceId:id,outcome:'UPDATED'})}audit(request,'BULK_ARCHIVE','SERVICE',ids.join(','),['status']);response.json({data:bulkResponse(ids,results)})}catch(error){next(error)}})
adminRouter.post('/services/bulk-delete',async(request,response,next)=>{const parsed=bulkIdsSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION',issues:parsed.error.issues}});const ids=[...new Set(parsed.data.serviceIds)];try{const records=await knownServices(ids),orderCounts=await prisma.order.groupBy({by:['serviceId'],where:{serviceId:{in:ids}},_count:true}),counts=new Map(orderCounts.map(x=>[x.serviceId,x._count]));const results:BulkItem[]=[];for(const id of ids){const current=records.get(id);if(!current&&!catalogIds.has(id)){results.push({serviceId:id,outcome:'FAILED',reason:'SERVICE_NOT_FOUND'});continue}if(!current?.isCustom||counts.has(id)){if(current?.status==='ARCHIVED'){results.push({serviceId:id,outcome:'SKIPPED',reason:counts.has(id)?'HAS_HISTORICAL_ORDERS':'PROTECTED_CODE_SERVICE'});continue}await prisma.catalogServiceOverride.upsert({where:{serviceId:id},create:{serviceId:id,titleKa:id,titleEn:id,descriptionKa:id,descriptionEn:id,category:'uncategorized',priceMinor:0,deliveryDays:1,status:'ARCHIVED',statusOnly:true,serviceSource:digitalStepIds.has(id)?'DIGITAL_STEP':'VERIFIED_PROVIDER',updatedByUserId:request.auth!.userId},update:{status:'ARCHIVED',updatedByUserId:request.auth!.userId}});results.push({serviceId:id,outcome:'ARCHIVED_INSTEAD',reason:counts.has(id)?'HAS_HISTORICAL_ORDERS':'PROTECTED_CODE_SERVICE'});continue}const assets=await prisma.serviceMedia.findMany({where:{serviceId:id},select:{publicId:true,type:true}});try{for(const asset of assets)await destroyServiceAsset(asset.publicId,asset.type==='IMAGE'?'image':'video')}catch{results.push({serviceId:id,outcome:'FAILED',reason:'MEDIA_DELETE_FAILED'});continue}await prisma.catalogServiceOverride.delete({where:{serviceId:id}});results.push({serviceId:id,outcome:'DELETED'})}audit(request,'BULK_DELETE','SERVICE',ids.join(','),[]);response.json({data:bulkResponse(ids,results)})}catch(error){next(error)}})

adminRouter.get('/subscriptions',async(request,response,next)=>{const parsed=pageSchema.safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search}=parsed.data;const where=search?{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}}]}:{};const[users,total]=await Promise.all([prisma.user.findMany({where,select:{id:true,firstName:true,lastName:true,email:true,...subscriptionUserSelect,updatedAt:true},orderBy:{updatedAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.user.count({where})]);const subscriptions=users.map(user=>{const effective=resolveEffectivePlan(user);return {...user,subscriptionPlan:effective.plan,source:effective.source}});response.json({data:{subscriptions,total,page,pageSize,distribution:[]}})}catch(error){next(error)}})

adminRouter.get('/ai-usage',async(request,response,next)=>{const parsed=pageSchema.safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search}=parsed.data;const where={...(search&&{user:{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}}]}})};const[usage,total]=await Promise.all([prisma.aIUsage.findMany({where,select:{id:true,feature:true,periodKey:true,requestCount:true,updatedAt:true,user:{select:{id:true,firstName:true,lastName:true,email:true,...subscriptionUserSelect}}},orderBy:{updatedAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.aIUsage.count({where})]);response.json({data:{usage:usage.map(row=>{const subscriptionPlan=resolveEffectivePlan(row.user).plan;return {...row,user:{...row.user,subscriptionPlan},limit:getUsageLimit(subscriptionPlan as SubscriptionPlan,featureMetric[row.feature])}}),total,page,pageSize}})}catch(error){next(error)}})
