import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { requireAdmin, requireAuth } from '../middleware/auth.js'
import { getUsageLimit, type SubscriptionPlan, type UsageMetric } from '../../shared/subscriptions.js'

export const adminRouter = Router()
adminRouter.use(requireAuth, requireAdmin)

const pageSchema = z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), search: z.string().trim().max(100).default('') })
const providerActionSchema = z.object({ action: z.enum(['VERIFY', 'SUSPEND', 'REINSTATE']) })
const featureMetric: Record<string, UsageMetric> = { AI_ASSISTANT:'AI_REQUESTS', POST_GENERATOR:'POST_GENERATIONS', CONTENT_IDEAS:'CONTENT_IDEA_GENERATIONS', MARKETING_PLANNER:'MARKETING_PLAN_GENERATIONS', BUSINESS_ANALYSIS:'BUSINESS_ANALYSIS_GENERATIONS' }

adminRouter.get('/overview', async (_request, response, next) => {
  try {
    const periodKey = new Date().toISOString().slice(0, 7)
    const [totalUsers, customers, providers, pendingProviders, verifiedProviders, suspendedProviders, totalOrders, completedOrders, activeOrders, orderValue, ai] = await Promise.all([
      prisma.user.count(), prisma.user.count({where:{role:'CUSTOMER'}}), prisma.user.count({where:{role:'PROVIDER'}}), prisma.user.count({where:{role:'PROVIDER',providerStatus:'PENDING'}}), prisma.user.count({where:{role:'PROVIDER',providerStatus:'VERIFIED'}}), prisma.user.count({where:{role:'PROVIDER',providerStatus:'SUSPENDED'}}), prisma.order.count(), prisma.order.count({where:{status:'COMPLETED'}}), prisma.order.count({where:{status:{in:['PENDING','CONFIRMED','IN_PROGRESS','IN_REVIEW']}}}), prisma.order.aggregate({_sum:{priceMinor:true}}), prisma.aIUsage.aggregate({where:{periodKey},_sum:{requestCount:true}}),
    ])
    response.json({data:{totalUsers,customers,providers,pendingProviders,verifiedProviders,suspendedProviders,totalOrders,completedOrders,activeOrders,totalOrderValueMinor:orderValue._sum.priceMinor??0,aiRequestsThisMonth:ai._sum.requestCount??0}})
  } catch (error) { next(error) }
})

adminRouter.get('/users', async (request, response, next) => {
  const parsed=pageSchema.extend({role:z.enum(['CUSTOMER','PROVIDER','ADMIN']).optional(),plan:z.enum(['FREE','PRO','BUSINESS']).optional()}).safeParse(request.query)
  if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}})
  try { const {page,pageSize,search,role,plan}=parsed.data; const where={...(role&&{role}),...(plan&&{subscriptionPlan:plan}),...(search&&{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}}]})}; const [users,total]=await Promise.all([prisma.user.findMany({where,select:{id:true,firstName:true,lastName:true,email:true,role:true,subscriptionPlan:true,providerStatus:true,createdAt:true,providerProfile:{select:{displayName:true}},_count:{select:{orders:true,aiUsage:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.user.count({where})]); response.json({data:{users,total,page,pageSize}}) } catch(error){next(error)}
})

adminRouter.get('/providers', async (request,response,next)=>{const parsed=pageSchema.extend({status:z.enum(['PENDING','VERIFIED','SUSPENDED']).optional()}).safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search,status}=parsed.data;const where={role:'PROVIDER' as const,...(status&&{providerStatus:status}),...(search&&{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}},{providerProfile:{displayName:{contains:search,mode:'insensitive' as const}}}]})};const[providers,total]=await Promise.all([prisma.user.findMany({where,select:{id:true,email:true,firstName:true,lastName:true,providerStatus:true,createdAt:true,providerProfile:{select:{slug:true,displayName:true,headline:true,description:true,category:true,website:true,location:true,languages:true,updatedAt:true}},_count:{select:{assignedOrders:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.user.count({where})]);response.json({data:{providers,total,page,pageSize}})}catch(error){next(error)}})

adminRouter.patch('/providers/:id/status', async(request,response,next)=>{const parsed=providerActionSchema.safeParse(request.body);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const provider=await prisma.user.findFirst({where:{id:request.params.id,role:'PROVIDER'},select:{id:true,providerStatus:true}});if(!provider)return response.status(404).json({error:{code:'PROVIDER_NOT_FOUND'}});const transitions={VERIFY:{from:['PENDING'],to:'VERIFIED'},SUSPEND:{from:['VERIFIED'],to:'SUSPENDED'},REINSTATE:{from:['SUSPENDED'],to:'VERIFIED'}} as const;const transition=transitions[parsed.data.action];if(!(transition.from as readonly string[]).includes(provider.providerStatus))return response.status(409).json({error:{code:'INVALID_PROVIDER_STATUS'}});const updated=await prisma.user.update({where:{id:provider.id},data:{providerStatus:transition.to},select:{id:true,providerStatus:true,updatedAt:true}});response.json({data:{provider:updated}})}catch(error){next(error)}})

adminRouter.get('/orders',async(request,response,next)=>{const parsed=pageSchema.extend({status:z.enum(['PENDING','CONFIRMED','IN_PROGRESS','IN_REVIEW','COMPLETED','CANCELLED']).optional()}).safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search,status}=parsed.data;const where={...(status&&{status}),...(search&&{OR:[{orderNumber:{contains:search,mode:'insensitive' as const}},{serviceTitleEn:{contains:search,mode:'insensitive' as const}},{serviceTitleKa:{contains:search,mode:'insensitive' as const}},{providerName:{contains:search,mode:'insensitive' as const}},{customer:{email:{contains:search,mode:'insensitive' as const}}}]})};const[orders,total]=await Promise.all([prisma.order.findMany({where,select:{id:true,orderNumber:true,serviceTitleKa:true,serviceTitleEn:true,providerName:true,packageNameKa:true,packageNameEn:true,priceMinor:true,currency:true,status:true,paymentStatus:true,createdAt:true,customer:{select:{firstName:true,lastName:true,email:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.order.count({where})]);response.json({data:{orders,total,page,pageSize}})}catch(error){next(error)}})

adminRouter.get('/subscriptions',async(request,response,next)=>{const parsed=pageSchema.safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search}=parsed.data;const where=search?{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}}]}:{};const[subscriptions,total,distribution]=await Promise.all([prisma.user.findMany({where,select:{id:true,firstName:true,lastName:true,email:true,subscriptionPlan:true,updatedAt:true},orderBy:{updatedAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.user.count({where}),prisma.user.groupBy({by:['subscriptionPlan'],_count:true})]);response.json({data:{subscriptions,total,page,pageSize,distribution}})}catch(error){next(error)}})

adminRouter.get('/ai-usage',async(request,response,next)=>{const parsed=pageSchema.safeParse(request.query);if(!parsed.success)return response.status(400).json({error:{code:'INVALID_ADMIN_ACTION'}});try{const{page,pageSize,search}=parsed.data;const where={...(search&&{user:{OR:[{email:{contains:search,mode:'insensitive' as const}},{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}}]}})};const[usage,total]=await Promise.all([prisma.aIUsage.findMany({where,select:{id:true,feature:true,periodKey:true,requestCount:true,updatedAt:true,user:{select:{id:true,firstName:true,lastName:true,email:true,subscriptionPlan:true}}},orderBy:{updatedAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),prisma.aIUsage.count({where})]);response.json({data:{usage:usage.map(row=>({...row,limit:getUsageLimit(row.user.subscriptionPlan as SubscriptionPlan,featureMetric[row.feature])})),total,page,pageSize}})}catch(error){next(error)}})
