import {Router} from 'express'
import rateLimit from 'express-rate-limit'
import {z} from 'zod'
import type {AIFeature,Prisma} from '@prisma/client'
import {prisma} from '../lib/prisma.js'
import {requireAuth} from '../middleware/auth.js'
import {AIService} from '../ai/service.js'
import {openAIProvider} from '../ai/openAIProvider.js'
import {AIProviderError} from '../ai/types.js'
import {aiConfig} from '../ai/config.js'
import {buildBusinessContext,type BusinessProfile} from '../../shared/businessProfile.js'
import {analysisFocusAreas,marketingChannels,marketingGoals,marketingTimeframes,type BusinessAnalysisInput,type MarketingPlanInput} from '../../shared/analysisTools.js'
import {canUseFeature,getUsageLimit,type StudioFeature,type UsageMetric} from '../../src/domain/subscriptions.js'

const marketingSchema=z.object({goal:z.enum(marketingGoals),budgetAmount:z.number().positive().max(100_000_000).optional(),currency:z.string().trim().min(3).max(3).optional(),timeframe:z.enum(marketingTimeframes),customStart:z.string().date().optional(),customEnd:z.string().date().optional(),selectedChannels:z.array(z.enum(marketingChannels)).max(11).optional(),priorityProductOrService:z.string().trim().max(500).optional(),campaignContext:z.string().trim().max(1500).optional(),customInstructions:z.string().trim().max(1000).optional(),language:z.enum(['KA','EN']).optional()}).strict().refine(x=>x.timeframe!=='CUSTOM'||Boolean(x.customStart&&x.customEnd))
const analysisSchema=z.object({focusArea:z.enum(analysisFocusAreas),currentChallenge:z.string().trim().max(1200).optional(),additionalContext:z.string().trim().max(2000).optional(),language:z.enum(['KA','EN']).optional()}).strict()
const service=new AIService(openAIProvider),periodKey=()=>new Date().toISOString().slice(0,7),limiter=rateLimit({windowMs:60_000,limit:6})
type Definition={feature:AIFeature&StudioFeature;metric:UsageMetric;invalid:string;failed:string;schema:typeof marketingSchema|typeof analysisSchema;generate:(input:MarketingPlanInput|BusinessAnalysisInput,context:ReturnType<typeof buildBusinessContext>|null,language:'KA'|'EN')=>Promise<unknown>}

function router(def:Definition){const result=Router();result.use(requireAuth)
  result.post('/generate',limiter,async(req,res)=>{const parsed=def.schema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:{code:def.invalid}});const userId=req.auth!.userId,a=await prisma.user.findUnique({where:{id:userId},select:{subscriptionPlan:true,preferredLocale:true,businessProfile:true}});if(!a)return res.status(401).json({error:{code:'UNAUTHENTICATED'}});if(!canUseFeature(a.subscriptionPlan,def.feature))return res.status(403).json({error:{code:'FORBIDDEN'}});const reservation=await reserve(userId,def.feature,getUsageLimit(a.subscriptionPlan,def.metric));if(!reservation)return res.status(429).json({error:{code:'AI_USAGE_LIMIT_REACHED'}});const started=Date.now();try{const profile=a.businessProfile as unknown as BusinessProfile|null,input=parsed.data as MarketingPlanInput|BusinessAnalysisInput,language=input.language??(profile?.preferredContentLanguage?.toLowerCase().startsWith('en')||a.preferredLocale==='en'?'EN':'KA'),output=await def.generate(input,profile?buildBusinessContext(profile):null,language);const saved=await prisma.$transaction(async tx=>{const generation=await tx.aIGeneration.create({data:{userId,businessProfileId:profile?.id,feature:def.feature,inputJson:input as Prisma.InputJsonValue,outputJson:output as Prisma.InputJsonValue},select:{id:true,createdAt:true}});const consumed=await tx.aIUsageReservation.deleteMany({where:{id:reservation.id,userId}});if(consumed.count!==1)throw new Error('AI usage reservation expired');await tx.aIUsage.update({where:{userId_feature_periodKey:{userId,feature:def.feature,periodKey:reservation.periodKey}},data:{requestCount:{increment:1}}});return generation});console.info('AI operation',{feature:def.feature,modelCategory:'analysis',success:true,durationMs:Date.now()-started});return res.json({data:{generation:{...saved,input,output}}})}catch(error){await prisma.aIUsageReservation.deleteMany({where:{id:reservation.id,userId}}).catch(()=>undefined);const code=error instanceof AIProviderError?(error.kind==='RESPONSE_INVALID'?'AI_RESPONSE_INVALID':'AI_PROVIDER_ERROR'):def.failed;console.error('AI operation',{feature:def.feature,modelCategory:'analysis',success:false,durationMs:Date.now()-started,code});return res.status(502).json({error:{code}})}})
  result.get('/history',async(req,res)=>{const rows=await prisma.aIGeneration.findMany({where:{userId:req.auth!.userId,feature:def.feature},orderBy:{createdAt:'desc'},take:12,select:{id:true,createdAt:true,inputJson:true}});res.json({data:{items:rows.map(x=>({id:x.id,createdAt:x.createdAt,input:x.inputJson}))}})})
  result.get('/history/:id',async(req,res)=>{const row=await prisma.aIGeneration.findFirst({where:{id:req.params.id,userId:req.auth!.userId,feature:def.feature},select:{id:true,createdAt:true,inputJson:true,outputJson:true}});if(!row)return res.status(404).json({error:{code:'NOT_FOUND'}});res.json({data:{generation:{id:row.id,createdAt:row.createdAt,input:row.inputJson,output:row.outputJson}}})});return result}
async function reserve(userId:string,feature:AIFeature,limit:number){const period=periodKey();return prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${userId}:${feature}:${period}`}, 0))`;await tx.aIUsageReservation.deleteMany({where:{expiresAt:{lte:new Date()}}});const usage=await tx.aIUsage.upsert({where:{userId_feature_periodKey:{userId,feature,periodKey:period}},create:{userId,feature,periodKey:period},update:{}});const active=await tx.aIUsageReservation.count({where:{userId,feature,periodKey:period,expiresAt:{gt:new Date()}}});if(usage.requestCount+active>=limit)return null;return tx.aIUsageReservation.create({data:{userId,feature,periodKey:period,expiresAt:new Date(Date.now()+aiConfig.reservationLeaseMs)},select:{id:true,periodKey:true}})})}
export const marketingPlannerRouter=router({feature:'MARKETING_PLANNER',metric:'MARKETING_PLAN_GENERATIONS',invalid:'INVALID_MARKETING_PLAN_REQUEST',failed:'MARKETING_PLAN_GENERATION_FAILED',schema:marketingSchema,generate:(input,context,language)=>service.generateMarketingPlan({request:input as MarketingPlanInput,businessContext:context,language})})
export const businessAnalysisRouter=router({feature:'BUSINESS_ANALYSIS',metric:'BUSINESS_ANALYSIS_GENERATIONS',invalid:'INVALID_BUSINESS_ANALYSIS_REQUEST',failed:'BUSINESS_ANALYSIS_FAILED',schema:analysisSchema,generate:(input,context,language)=>service.generateBusinessAnalysis({request:input as BusinessAnalysisInput,businessContext:context,language})})
