import {Router} from 'express'
import rateLimit from 'express-rate-limit'
import {z} from 'zod'
import type {Prisma} from '@prisma/client'
import {prisma} from '../lib/prisma.js'
import {requireAuth} from '../middleware/auth.js'
import {AIService} from '../ai/service.js'
import {openAIProvider} from '../ai/openAIProvider.js'
import {AIProviderError} from '../ai/types.js'
import {aiConfig} from '../ai/config.js'
import {buildBusinessContext,type BusinessProfile} from '../../shared/businessProfile.js'
import {contentPillars,ideaObjectives,ideaPlatforms,ideaTimeframes,type ContentIdeaInput} from '../../shared/contentIdeas.js'
import {canUseFeature,getUsageLimit} from '../../src/domain/subscriptions.js'

export const contentIdeasRouter=Router();contentIdeasRouter.use(requireAuth)
const service=new AIService(openAIProvider),periodKey=()=>new Date().toISOString().slice(0,7)
const schema=z.object({platforms:z.array(z.enum(ideaPlatforms)).min(1).max(4),objective:z.enum(ideaObjectives),contentPillars:z.array(z.enum(contentPillars)).max(10).default([]),timeframe:z.enum(ideaTimeframes),ideaCount:z.union([z.literal(3),z.literal(5),z.literal(10)]),customInstructions:z.string().trim().max(1000).optional(),language:z.enum(['KA','EN']).optional()}).strict()
async function context(userId:string){return prisma.user.findUnique({where:{id:userId},select:{subscriptionPlan:true,preferredLocale:true,businessProfile:true}})}
async function usage(userId:string,plan:'FREE'|'PRO'|'BUSINESS'){const period=periodKey(),limit=getUsageLimit(plan,'CONTENT_IDEA_GENERATIONS'),row=await prisma.aIUsage.findUnique({where:{userId_feature_periodKey:{userId,feature:'CONTENT_IDEAS',periodKey:period}}});return {used:row?.requestCount??0,limit,remaining:Math.max(0,limit-(row?.requestCount??0)),period}}
async function reserve(userId:string,limit:number){const period=periodKey();return prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${userId}:CONTENT_IDEAS:${period}`}, 0))`;await tx.aIUsageReservation.deleteMany({where:{expiresAt:{lte:new Date()}}});const row=await tx.aIUsage.upsert({where:{userId_feature_periodKey:{userId,feature:'CONTENT_IDEAS',periodKey:period}},create:{userId,feature:'CONTENT_IDEAS',periodKey:period},update:{}});const active=await tx.aIUsageReservation.count({where:{userId,feature:'CONTENT_IDEAS',periodKey:period,expiresAt:{gt:new Date()}}});if(row.requestCount+active>=limit)return null;return tx.aIUsageReservation.create({data:{userId,feature:'CONTENT_IDEAS',periodKey:period,expiresAt:new Date(Date.now()+aiConfig.reservationLeaseMs)},select:{id:true,periodKey:true}})})}
contentIdeasRouter.get('/history',async(req,res)=>{const rows=await prisma.aIGeneration.findMany({where:{userId:req.auth!.userId,feature:'CONTENT_IDEAS'},orderBy:{createdAt:'desc'},take:20,select:{id:true,inputJson:true,outputJson:true,createdAt:true}});res.json({data:{generations:rows.map(x=>({id:x.id,input:x.inputJson,output:x.outputJson,createdAt:x.createdAt}))}})})
contentIdeasRouter.post('/generate',rateLimit({windowMs:60_000,limit:6}),async(req,res)=>{const parsed=schema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:{code:'INVALID_CONTENT_IDEA_REQUEST'}});const userId=req.auth!.userId,a=await context(userId);if(!a)return res.status(401).json({error:{code:'UNAUTHENTICATED'}});if(!canUseFeature(a.subscriptionPlan,'CONTENT_IDEAS'))return res.status(403).json({error:{code:'FORBIDDEN'}});const reservation=await reserve(userId,getUsageLimit(a.subscriptionPlan,'CONTENT_IDEA_GENERATIONS'));if(!reservation)return res.status(429).json({error:{code:'AI_USAGE_LIMIT_REACHED'}});try{const profile=a.businessProfile as unknown as BusinessProfile|null,input=parsed.data as ContentIdeaInput,language=input.language??(profile?.preferredContentLanguage?.startsWith('en')?'EN':a.preferredLocale==='en'?'EN':'KA'),output=await service.generateContentIdeas({request:input,businessContext:profile?buildBusinessContext(profile):null,language});const generation=await prisma.$transaction(async tx=>{const saved=await tx.aIGeneration.create({data:{userId,businessProfileId:profile?.id,feature:'CONTENT_IDEAS',inputJson:input as unknown as Prisma.InputJsonValue,outputJson:output as unknown as Prisma.InputJsonValue},select:{id:true,createdAt:true}});const consumed=await tx.aIUsageReservation.deleteMany({where:{id:reservation.id,userId}});if(consumed.count!==1)throw new Error('AI usage reservation expired');await tx.aIUsage.update({where:{userId_feature_periodKey:{userId,feature:'CONTENT_IDEAS',periodKey:reservation.periodKey}},data:{requestCount:{increment:1}}});return saved});return res.json({data:{generation:{...generation,input,output},usage:await usage(userId,a.subscriptionPlan)}})}catch(error){await prisma.aIUsageReservation.deleteMany({where:{id:reservation.id,userId}}).catch(()=>undefined);const code=error instanceof AIProviderError&&error.kind==='RESPONSE_INVALID'?'AI_RESPONSE_INVALID':error instanceof AIProviderError?'CONTENT_IDEA_GENERATION_FAILED':'INTERNAL_ERROR';return res.status(502).json({error:{code}})}})
