import {Router} from 'express'
import {z} from 'zod'
import {prisma} from '../lib/prisma.js'
import {requireAuth} from '../middleware/auth.js'
import {contentTypes,ideaPlatforms} from '../../shared/contentIdeas.js'
export const contentItemsRouter=Router();contentItemsRouter.use(requireAuth)
const statuses=['IDEA','DRAFT','READY','SCHEDULED','PUBLISHED'] as const,sources=['MANUAL','AI_CONTENT_IDEA','AI_POST_GENERATOR'] as const
const fields={title:z.string().trim().min(1).max(300),caption:z.string().max(10000),notes:z.string().max(3000).nullable().optional(),platform:z.enum(ideaPlatforms),contentType:z.enum(contentTypes),status:z.enum(statuses),scheduledAt:z.string().datetime().nullable()}
const createSchema=z.object({...fields,caption:fields.caption.default(''),source:z.enum(sources).optional(),sourceGenerationId:z.string().cuid().nullable().optional()}).strict()
// PATCH must not inherit creation defaults: omitted fields stay unchanged.
const updateSchema=z.object(fields).partial().strict()
contentItemsRouter.get('/',async(req,res)=>{const q=z.object({from:z.string().datetime().optional(),to:z.string().datetime().optional(),status:z.enum(statuses).optional(),platform:z.enum(ideaPlatforms).optional(),contentType:z.enum(contentTypes).optional()}).safeParse(req.query);if(!q.success)return res.status(400).json({error:{code:'INVALID_CONTENT_ITEM'}});const d=q.data;const items=await prisma.contentItem.findMany({where:{userId:req.auth!.userId,status:d.status,platform:d.platform,contentType:d.contentType,scheduledAt:d.from||d.to?{gte:d.from?new Date(d.from):undefined,lte:d.to?new Date(d.to):undefined}:undefined},orderBy:[{scheduledAt:'asc'},{createdAt:'desc'}],take:500});res.json({data:{items}})})
contentItemsRouter.post('/',async(req,res)=>{const p=createSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:{code:'INVALID_CONTENT_ITEM'}});const source=p.data.source??'MANUAL';let generation=null;if(p.data.sourceGenerationId){generation=await prisma.aIGeneration.findFirst({where:{id:p.data.sourceGenerationId,userId:req.auth!.userId}});if(!generation)return res.status(400).json({error:{code:'INVALID_CONTENT_ITEM'}})}const item=await prisma.contentItem.create({data:{...p.data,userId:req.auth!.userId,source,scheduledAt:p.data.scheduledAt?new Date(p.data.scheduledAt):null,businessProfileId:generation?.businessProfileId}});res.status(201).json({data:{item}})})
contentItemsRouter.patch('/:id',async(req,res)=>{const id=z.string().cuid().safeParse(req.params.id),p=updateSchema.safeParse(req.body);if(!id.success||!p.success)return res.status(400).json({error:{code:'INVALID_CONTENT_ITEM'}});const owned=await prisma.contentItem.findFirst({where:{id:id.data,userId:req.auth!.userId},select:{id:true}});if(!owned)return res.status(404).json({error:{code:'CONTENT_ITEM_NOT_FOUND'}});const item=await prisma.contentItem.update({where:{id:id.data},data:{...p.data,scheduledAt:p.data.scheduledAt===undefined?undefined:p.data.scheduledAt?new Date(p.data.scheduledAt):null}});res.json({data:{item}})})
contentItemsRouter.delete('/:id',async(req,res)=>{const id=z.string().cuid().safeParse(req.params.id);if(!id.success)return res.status(404).json({error:{code:'CONTENT_ITEM_NOT_FOUND'}});const result=await prisma.contentItem.deleteMany({where:{id:id.data,userId:req.auth!.userId}});if(result.count)res.status(204).end();else res.status(404).json({error:{code:'CONTENT_ITEM_NOT_FOUND'}})})
