import { randomBytes } from 'node:crypto'
import { Router } from 'express'
import { prisma } from '../lib/prisma.js'
import { requireAuth } from '../middleware/auth.js'
import { createOrderSchema } from '../validation/orders.js'
import { findOrderService } from '../../shared/orderCatalog.js'
export const ordersRouter=Router()
ordersRouter.use(requireAuth)
interface StoredOrder{id:string;orderNumber:string;serviceId:string;serviceSlug:string;serviceTitleKa:string;serviceTitleEn:string;providerSlug:string;providerName:string;packageId:string;packageNameKa:string;packageNameEn:string;priceMinor:number;currency:string;status:string;paymentStatus:string;requirementsText:string;referenceLinks:unknown;deliveryDate:Date;createdAt:Date;updatedAt:Date}
const safe=(o:StoredOrder)=>({id:o.id,orderNumber:o.orderNumber,serviceId:o.serviceId,serviceSlug:o.serviceSlug,serviceTitle:{ka:o.serviceTitleKa,en:o.serviceTitleEn},providerSlug:o.providerSlug,providerName:o.providerName,packageId:o.packageId,packageName:{ka:o.packageNameKa,en:o.packageNameEn},priceMinor:o.priceMinor,currency:o.currency,status:o.status,paymentStatus:o.paymentStatus,requirements:o.requirementsText,referenceLinks:Array.isArray(o.referenceLinks)?o.referenceLinks:[],deliveryDate:o.deliveryDate,createdAt:o.createdAt,updatedAt:o.updatedAt})
ordersRouter.post('/',async(req,res,next)=>{const parsed=createOrderSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:{code:'INVALID_ORDER_REQUEST'}});const service=findOrderService(parsed.data.serviceSlug);if(!service)return res.status(404).json({error:{code:'SERVICE_NOT_FOUND'}});const pack=service.packages.find(p=>p.id===parsed.data.packageId);if(!pack)return res.status(404).json({error:{code:'PACKAGE_NOT_FOUND'}});const now=new Date();const deliveryDate=new Date(now);deliveryDate.setUTCDate(deliveryDate.getUTCDate()+pack.deliveryDays);try{const provider=await prisma.user.findFirst({where:{providerSlug:service.providerSlug,role:'PROVIDER'},select:{id:true}});const order=await prisma.order.create({data:{orderNumber:`DS-${randomBytes(6).toString('hex').toUpperCase()}`,customerId:req.auth!.userId,providerUserId:provider?.id,serviceId:service.id,serviceSlug:service.slug,serviceTitleKa:service.title.ka,serviceTitleEn:service.title.en,providerSlug:service.providerSlug,providerName:service.providerName,packageId:pack.id,packageNameKa:pack.name.ka,packageNameEn:pack.name.en,priceMinor:pack.priceMinor,requirementsText:parsed.data.requirements,referenceLinks:parsed.data.referenceLinks??[],deliveryDate}});return res.status(201).json({data:{order:safe(order)}})}catch(e){next(e)}})
ordersRouter.get('/',async(req,res,next)=>{try{const orders=await prisma.order.findMany({where:{customerId:req.auth!.userId},orderBy:{createdAt:'desc'}});res.json({data:{orders:orders.map(safe)}})}catch(e){next(e)}})
ordersRouter.get('/:id',async(req,res,next)=>{try{const order=await prisma.order.findFirst({where:{id:req.params.id,customerId:req.auth!.userId}});if(!order)return res.status(404).json({error:{code:'ORDER_NOT_FOUND'}});res.json({data:{order:safe(order)}})}catch(e){next(e)}})
