import {Router} from 'express'
import rateLimit from 'express-rate-limit'
import {z} from 'zod'
import type {Prisma} from '@prisma/client'
import {prisma} from '../lib/prisma.js'
import {requireAuth} from '../middleware/auth.js'
import {AIService} from '../ai/service.js'
import {openAIProvider} from '../ai/openAIProvider.js'
import {AIProviderError} from '../ai/types.js'
import {aiConfig} from '../ai/config.js'
import {buildBusinessContext,type BusinessProfile} from '../../shared/businessProfile.js'
import {postLanguages,postObjectives,postPlatforms,postTones,type PostGenerationInput,type PostGenerationOutput} from '../../shared/postGenerator.js'
import {canUseFeature,getUsageLimit} from '../../src/domain/subscriptions.js'

export const postGeneratorRouter=Router();postGeneratorRouter.use(requireAuth)
const service=new AIService(openAIProvider),periodKey=()=>new Date().toISOString().slice(0,7)
const requestSchema=z.object({platform:z.enum(postPlatforms),objective:z.enum(postObjectives),language:z.enum(postLanguages),tone:z.enum(postTones),topic:z.string().trim().min(2).max(500),keyMessage:z.string().trim().max(1000).optional(),offer:z.string().trim().max(500).optional(),callToAction:z.string().trim().max(300).optional(),customInstructions:z.string().trim().max(1000).optional(),variationCount:z.union([z.literal(1),z.literal(2),z.literal(3)])}).strict()
const id=z.string().cuid(),limiter=rateLimit({windowMs:60_000,limit:8,standardHeaders:true,legacyHeaders:false,handler:(_q,r)=>r.status(429).json({error:{code:'RATE_LIMITED'}})})
async function access(userId:string){return prisma.user.findUnique({where:{id:userId},select:{subscriptionPlan:true,businessProfile:true}})}
async function usage(userId:string,plan:'FREE'|'PRO'|'BUSINESS'){const period=periodKey(),limit=getUsageLimit(plan,'POST_GENERATIONS'),row=await prisma.aIUsage.findUnique({where:{userId_feature_periodKey:{userId,feature:'POST_GENERATOR',periodKey:period}}});return {plan,feature:'POST_GENERATOR',used:row?.requestCount??0,limit,remaining:Math.max(0,limit-(row?.requestCount??0)),period}}
async function reserve(userId:string,limit:number){const period=periodKey();return prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${userId}:POST_GENERATOR:${period}`}, 0))`;await tx.aIUsageReservation.deleteMany({where:{expiresAt:{lte:new Date()}}});const row=await tx.aIUsage.upsert({where:{userId_feature_periodKey:{userId,feature:'POST_GENERATOR',periodKey:period}},create:{userId,feature:'POST_GENERATOR',periodKey:period},update:{}});const active=await tx.aIUsageReservation.count({where:{userId,feature:'POST_GENERATOR',periodKey:period,expiresAt:{gt:new Date()}}});if(row.requestCount+active>=limit)return null;return tx.aIUsageReservation.create({data:{userId,feature:'POST_GENERATOR',periodKey:period,expiresAt:new Date(Date.now()+aiConfig.reservationLeaseMs)},select:{id:true,periodKey:true}})})}

postGeneratorRouter.get('/usage',async(req,res)=>{const a=await access(req.auth!.userId);return a?res.json({data:await usage(req.auth!.userId,a.subscriptionPlan)}):res.status(401).json({error:{code:'UNAUTHENTICATED'}})})
postGeneratorRouter.get('/history',async(req,res)=>{const rows=await prisma.aIGeneration.findMany({where:{userId:req.auth!.userId,feature:'POST_GENERATOR'},orderBy:{createdAt:'desc'},take:20,select:{id:true,inputJson:true,outputJson:true,createdAt:true}});return res.json({data:{generations:rows.map(x=>({id:x.id,input:x.inputJson,output:x.outputJson,createdAt:x.createdAt}))}})})
postGeneratorRouter.delete('/history/:id',async(req,res)=>{if(!id.safeParse(req.params.id).success)return res.status(404).json({error:{code:'GENERATION_NOT_FOUND'}});const result=await prisma.aIGeneration.deleteMany({where:{id:req.params.id,userId:req.auth!.userId,feature:'POST_GENERATOR'}});return result.count?res.status(204).end():res.status(404).json({error:{code:'GENERATION_NOT_FOUND'}})})
postGeneratorRouter.post('/generate',limiter,async(req,res)=>{const parsed=requestSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:{code:'INVALID_GENERATION_REQUEST'}});const userId=req.auth!.userId,a=await access(userId);if(!a)return res.status(401).json({error:{code:'UNAUTHENTICATED'}});if(!canUseFeature(a.subscriptionPlan,'POST_GENERATOR'))return res.status(403).json({error:{code:'FORBIDDEN'}});const reservation=await reserve(userId,getUsageLimit(a.subscriptionPlan,'POST_GENERATIONS'));if(!reservation)return res.status(429).json({error:{code:'AI_USAGE_LIMIT_REACHED'}});const started=Date.now();try{const input=parsed.data as PostGenerationInput,profile=a.businessProfile as unknown as BusinessProfile|null,output=await service.generatePost({request:input,businessContext:profile?buildBusinessContext(profile):null});const generation=await prisma.$transaction(async tx=>{const saved=await tx.aIGeneration.create({data:{userId,businessProfileId:profile?.id,feature:'POST_GENERATOR',inputJson:input as unknown as Prisma.InputJsonValue,outputJson:output as unknown as Prisma.InputJsonValue},select:{id:true,createdAt:true}});const consumed=await tx.aIUsageReservation.deleteMany({where:{id:reservation.id,userId,periodKey:reservation.periodKey}});if(consumed.count!==1)throw new Error('AI usage reservation expired');await tx.aIUsage.update({where:{userId_feature_periodKey:{userId,feature:'POST_GENERATOR',periodKey:reservation.periodKey}},data:{requestCount:{increment:1}}});return saved});console.info('AI operation',{feature:'POST_GENERATOR',success:true,durationMs:Date.now()-started});return res.json({data:{generation:{...generation,input,output},usage:await usage(userId,a.subscriptionPlan)}})}catch(error){await prisma.aIUsageReservation.deleteMany({where:{id:reservation.id,userId}}).catch(()=>undefined);const code=error instanceof AIProviderError?(error.kind==='RESPONSE_INVALID'?'AI_RESPONSE_INVALID':'AI_PROVIDER_ERROR'):'INTERNAL_ERROR';console.error('AI operation',{feature:'POST_GENERATOR',success:false,durationMs:Date.now()-started,code});return res.status(502).json({error:{code}})}})
const calendarBase={generationId:z.string().cuid(),variationIndex:z.number().int().min(0).max(2)}
const calendarSchema=z.discriminatedUnion('status',[
  z.object({...calendarBase,status:z.literal('SCHEDULED'),scheduledAt:z.string().datetime()}).strict(),
  z.object({...calendarBase,status:z.enum(['IDEA','DRAFT','READY']),scheduledAt:z.null().optional()}).strict(),
])
postGeneratorRouter.post('/calendar',async(req,res)=>{const parsed=calendarSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:{code:'INVALID_GENERATION_REQUEST'}});const generation=await prisma.aIGeneration.findFirst({where:{id:parsed.data.generationId,userId:req.auth!.userId,feature:'POST_GENERATOR'}});if(!generation)return res.status(404).json({error:{code:'GENERATION_NOT_FOUND'}});const input=generation.inputJson as unknown as PostGenerationInput,output=generation.outputJson as unknown as PostGenerationOutput,variation=output.variations[parsed.data.variationIndex];if(!variation||!postPlatforms.includes(input.platform))return res.status(400).json({error:{code:'INVALID_GENERATION_REQUEST'}});const item=await prisma.contentItem.create({data:{userId:req.auth!.userId,businessProfileId:generation.businessProfileId,title:variation.headline,caption:variation.caption,platform:input.platform,status:parsed.data.status,scheduledAt:parsed.data.status==='SCHEDULED'?new Date(parsed.data.scheduledAt):null,source:'AI_POST_GENERATOR',sourceGenerationId:generation.id}});return res.status(201).json({data:{item}})})
postGeneratorRouter.get('/calendar',async(req,res)=>{const items=await prisma.contentItem.findMany({where:{userId:req.auth!.userId},orderBy:[{scheduledAt:'asc'},{createdAt:'desc'}],take:100});return res.json({data:{items}})})
