import { useEffect, useId, useMemo, useState } from 'react'
import { ChevronDown, Clock3, Grid2X2, Heart, List, SearchX, SlidersHorizontal, Star, X } from 'lucide-react'
import { catalogServices, categories, type Service } from '../../data/marketplace'
import { dictionary, localePath, type Locale } from '../../i18n'
import { MarketplaceIcon } from './Icon'
import { ServiceCard } from './ServiceCard'

type SortKey = 'recommended'|'popular'|'rated'|'priceLow'|'priceHigh'|'newest'
type View = 'grid'|'list'
type Filters = { categories:string[]; min:number; max:number; rating:number; delivery:number; serviceTypes:string[]; providerTypes:string[] }
const initialFilters: Filters = {categories:[],min:0,max:1000,rating:0,delivery:0,serviceTypes:[],providerTypes:[]}
const interpolate = (value:string, vars:Record<string,string|number>) => Object.entries(vars).reduce((text,[key,replacement])=>text.replace(`{${key}}`,String(replacement)),value)
const categoryChips: Partial<Record<string, Record<Locale, string[]>>> = {
 social: {ka:['Facebook','Instagram','TikTok','კონტენტ გეგმა','რეკლამა','დიზაინი','ვიდეო'],en:['Facebook','Instagram','TikTok','Content Planning','Advertising','Design','Video']},
 web: {ka:['ბიზნეს ვებსაიტი','ლენდინგ გვერდი','ონლაინ მაღაზია','UI/UX','ტექნიკური მხარდაჭერა'],en:['Business Website','Landing Page','Online Store','UI/UX','Technical Support']},
 design: {ka:['ლოგო','ბრენდინგი','UI/UX','სოციალური მედიის დიზაინი','პრეზენტაცია'],en:['Logo','Branding','UI/UX','Social Media Design','Presentation']},
 ai: {ka:['AI კონტენტი','AI ავტომატიზაცია','სამუშაო პროცესები','კონსულტაცია'],en:['AI Content','AI Automation','Workflows','Consultation']},
}

function ServicePrice({service,locale}:{service:Service;locale:Locale}) { return <strong>{locale==='ka'?`${service.price}₾-დან`:`From ${service.price}₾`}</strong> }
function FavoriteButton({locale}:{locale:Locale}) { const [active,setActive]=useState(false); const t=dictionary[locale]; return <button className="favorite" type="button" aria-pressed={active} aria-label={active?t.home.removeFavorite:t.home.addFavorite} onClick={()=>setActive(v=>!v)}><Heart fill={active?'currentColor':'none'} aria-hidden="true"/></button> }
function ServiceListItem({service,locale}:{service:Service;locale:Locale}) { const t=dictionary[locale]; return <article className="service-list-item"><div className={`service-preview preview-${service.preview}`} aria-hidden="true"><span/><span/><span/></div><div className="list-main"><div className="inline-badges">{service.badges.slice(0,2).map(b=><span key={b}>{t.badges[b]}</span>)}</div><a className="service-title" href={localePath(locale,'/marketplace')}>{service.title[locale]}</a><p>{service.description[locale]}</p><div className="provider"><span>{service.provider.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>{service.provider}</div></div><div className="list-aside"><FavoriteButton locale={locale}/><span className="rating"><Star fill="currentColor" aria-hidden="true"/> {service.rating} <small>({service.reviews})</small></span><span className="delivery"><Clock3/>{interpolate(t.catalog.deliveryDays,{count:service.deliveryDays})}</span><ServicePrice service={service} locale={locale}/><a className="compact-button" href={localePath(locale,'/marketplace')}>{t.catalog.viewDetails}</a></div></article> }

function FilterGroup({legend,children}:{legend:string;children:React.ReactNode}) { return <fieldset className="filter-group"><legend>{legend}</legend>{children}</fieldset> }
function Check({checked,onChange,label,meta}:{checked:boolean;onChange:()=>void;label:string;meta?:string|number}) { return <label className="filter-option"><input type="checkbox" checked={checked} onChange={onChange}/><span>{label}</span>{meta!==undefined&&<small>{meta}</small>}</label> }
type FilterProps={locale:Locale;value:Filters;onChange:(next:Filters)=>void;onClear:()=>void;onApply?:()=>void}
export function MarketplaceFilters({locale,value,onChange,onClear,onApply}:FilterProps) { const t=dictionary[locale].catalog; const updateList=(key:'categories'|'serviceTypes'|'providerTypes',item:string)=>onChange({...value,[key]:value[key].includes(item)?value[key].filter(x=>x!==item):[...value[key],item]}); return <div className="marketplace-filters">
 <FilterGroup legend={t.category}>{categories.map(c=><Check key={c.id} label={c.name[locale]} meta={catalogServices.filter(s=>s.category===c.id).length} checked={value.categories.includes(c.id)} onChange={()=>updateList('categories',c.id)}/>)}</FilterGroup>
 <FilterGroup legend={t.price}><div className="price-inputs"><label>{t.min}<span><input type="number" min="0" max={value.max} value={value.min} onChange={e=>onChange({...value,min:Number(e.target.value)})}/><b>₾</b></span></label><i>—</i><label>{t.max}<span><input type="number" min={value.min} value={value.max} onChange={e=>onChange({...value,max:Number(e.target.value)})}/><b>₾</b></span></label></div></FilterGroup>
 <FilterGroup legend={t.rating}>{[4.5,4,3.5].map(r=><label className="filter-option" key={r}><input type="radio" name="rating" checked={value.rating===r} onChange={()=>onChange({...value,rating:r})}/><span className="stars">★</span><span>{r}+</span></label>)}</FilterGroup>
 <FilterGroup legend={t.delivery}>{[[0,t.anyDelivery],[1,t.dayOne],[3,t.dayThree],[7,t.daySeven]].map(([days,label])=><label className="filter-option" key={days}><input type="radio" name="delivery" checked={value.delivery===days} onChange={()=>onChange({...value,delivery:Number(days)})}/><span>{label}</span></label>)}</FilterGroup>
 <FilterGroup legend={t.serviceType}>{(['oneTime','monthly','consultation'] as const).map(key=><Check key={key} label={t[key]} checked={value.serviceTypes.includes(key)} onChange={()=>updateList('serviceTypes',key)}/>)}</FilterGroup>
 <FilterGroup legend={t.providerType}>{(['agency','specialist','digitalStep'] as const).map(key=><Check key={key} label={t[key]} checked={value.providerTypes.includes(key)} onChange={()=>updateList('providerTypes',key)}/>)}</FilterGroup>
 <div className="filter-actions"><button type="button" className="clear-button" onClick={onClear}>{t.clear}</button>{onApply&&<button type="button" className="apply-button" onClick={onApply}>{t.showResults}</button>}</div>
 </div> }

function EmptyState({locale,onClear,recoveryHref}:{locale:Locale;onClear:()=>void;recoveryHref?:string}) { const t=dictionary[locale].catalog; return <div className="catalog-empty"><span><SearchX/></span><h2>{t.noResults}</h2><p>{t.noResultsText}</p>{recoveryHref?<a className="empty-state-action" href={recoveryHref}>{t.clear}</a>:<button type="button" onClick={onClear}>{t.clear}</button>}</div> }
function SortControl({locale,value,onChange}:{locale:Locale;value:SortKey;onChange:(v:SortKey)=>void}) { const t=dictionary[locale].catalog; return <label className="sort-control"><span>{t.sort}</span><div><select aria-label={t.sort} value={value} onChange={e=>onChange(e.target.value as SortKey)}>{(['recommended','popular','rated','priceLow','priceHigh','newest'] as const).map(k=><option key={k} value={k}>{t[k]}</option>)}</select><ChevronDown aria-hidden="true"/></div></label> }

type CatalogProps={locale:Locale;categorySlug?:string;searchQuery?:string}
export function Catalog({locale,categorySlug,searchQuery}:CatalogProps) { const t=dictionary[locale].catalog; const initialCategory=categories.find(c=>c.id===categorySlug); const [filters,setFilters]=useState<Filters>(()=>({...initialFilters,categories:initialCategory?[initialCategory.id]:[]})); const [sort,setSort]=useState<SortKey>('recommended'); const [view,setView]=useState<View>('grid'); const [drawer,setDrawer]=useState(false); const drawerTitle=useId();
 useEffect(()=>{if(!drawer)return; const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(false)}; document.addEventListener('keydown',close); return()=>document.removeEventListener('keydown',close)},[drawer])
 const clear=()=>setFilters({...initialFilters,categories:initialCategory?[initialCategory.id]:[]});
 const results=useMemo(()=>{const filtered=catalogServices.filter(s=>(!filters.categories.length||filters.categories.includes(s.category))&&s.price>=filters.min&&s.price<=filters.max&&s.rating>=filters.rating&&(!filters.delivery||s.deliveryDays<=filters.delivery)&&(!filters.serviceTypes.length||filters.serviceTypes.includes(s.serviceType))&&(!filters.providerTypes.length||filters.providerTypes.includes(s.providerType))&&(searchQuery===undefined||`${s.title.ka} ${s.title.en} ${s.description.ka} ${s.description.en} ${s.provider}`.toLowerCase().includes(searchQuery.toLowerCase()))); return filtered.map((service,index)=>({service,index})).sort((a,b)=>{const d=sort==='popular'?b.service.reviews-a.service.reviews:sort==='rated'?b.service.rating-a.service.rating:sort==='priceLow'?a.service.price-b.service.price:sort==='priceHigh'?b.service.price-a.service.price:sort==='newest'?b.service.createdOrder-a.service.createdOrder:0; return d||a.index-b.index}).map(x=>x.service)},[filters,sort,searchQuery]);
 const subcategories=initialCategory?categoryChips[initialCategory.id]?.[locale]:undefined;
 const title=searchQuery!==undefined?interpolate(t.searchTitle,{query:searchQuery||t.searchDefault}):initialCategory?initialCategory.name[locale]:t.allServices;
 return <div className="catalog-page"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href={localePath(locale,'/')}>{t.home}</a><span>/</span>{initialCategory&&<><a href={localePath(locale,'/marketplace')}>{t.marketplace}</a><span>/</span></>}<strong>{title}</strong></nav>
  <header className={`catalog-header ${initialCategory?'category-header':''}`}>{initialCategory&&<span className="catalog-category-icon"><MarketplaceIcon name={initialCategory.icon}/></span>}<div><p className="catalog-eyebrow">{searchQuery!==undefined?t.searchDemo:t.marketplace}</p><h1>{title}</h1><p>{initialCategory?initialCategory.description[locale]:t.subtitle}</p><strong>{interpolate(searchQuery!==undefined?t.resultsFound:t.servicesFound,{count:results.length})}</strong></div></header>
  {subcategories&&<section className="subcategory-section" aria-labelledby="subcategory-title"><h2 id="subcategory-title">{t.subcategories}</h2><div className="subcategory-chips">{subcategories.map(x=><button type="button" key={x}>{x}</button>)}</div></section>}
  <div className="catalog-layout"><aside className="filter-sidebar" aria-label={t.filters}><MarketplaceFilters locale={locale} value={filters} onChange={setFilters} onClear={clear}/></aside><section className="catalog-results" aria-label={t.categoryServices}><div className="results-toolbar"><p>{interpolate(searchQuery!==undefined?t.resultsFound:t.servicesFound,{count:results.length})}</p><div className="catalog-controls"><button className="mobile-filter-button" type="button" onClick={()=>setDrawer(true)}><SlidersHorizontal/>{t.filters}</button><SortControl locale={locale} value={sort} onChange={setSort}/><div className="view-switch" role="group" aria-label={`${t.grid} / ${t.list}`}><button type="button" aria-label={t.grid} aria-pressed={view==='grid'} onClick={()=>setView('grid')}><Grid2X2/></button><button type="button" aria-label={t.list} aria-pressed={view==='list'} onClick={()=>setView('list')}><List/></button></div></div></div>
  {results.length===0?<EmptyState locale={locale} onClear={clear} recoveryHref={searchQuery!==undefined?localePath(locale,'/marketplace'):undefined}/>:view==='grid'?<div className="catalog-grid">{results.map(s=><ServiceCard key={s.id} service={s} locale={locale}/>)}</div>:<div className="catalog-list">{results.map(s=><ServiceListItem key={s.id} service={s} locale={locale}/>)}</div>}</section></div>
  {drawer&&<div className="filter-drawer-layer" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setDrawer(false)}}><section className="filter-drawer" role="dialog" aria-modal="true" aria-labelledby={drawerTitle}><header><h2 id={drawerTitle}>{t.filters}</h2><button type="button" aria-label={t.close} onClick={()=>setDrawer(false)}><X/></button></header><div className="drawer-scroll"><MarketplaceFilters locale={locale} value={filters} onChange={setFilters} onClear={clear} onApply={()=>setDrawer(false)}/></div></section></div>}
 </div> }

export function CatalogSkeleton({category=false}:{category?:boolean}) { return <div className="catalog-skeleton" aria-hidden="true">{category&&<div className="skeleton category-header-skeleton"/>}<div className="skeleton catalog-title-skeleton"/><div className="catalog-layout"><div className="skeleton filter-skeleton"/><div className="skeleton-catalog-grid">{Array.from({length:6},(_,i)=><div className="skeleton card-skeleton" key={i}/>)}</div></div></div> }
