import { useEffect, useId, useMemo, useState, type FormEvent } from 'react'
import { ChevronDown, Clock3, Grid2X2, Heart, List, Search, SearchX, SlidersHorizontal, Star, X } from 'lucide-react'
import { catalogServices, categories, isServicePublic, type Service } from '../../data/marketplace'
import { toggleFavorite, useFavorites } from '../../lib/favorites'
import { dictionary, localePath, type Locale } from '../../i18n'
import { MarketplaceIcon } from './Icon'
import { ServiceCard, ServiceMedia, ServicePrice, ServiceSourceBadge } from './ServiceCard'

type SortKey = 'recommended'|'priceLow'|'priceHigh'|'newest'
type View = 'grid'|'list'
type Filters = {categories:string[];min:string;max:string;delivery:number;serviceTypes:string[];sources:string[]}
const emptyFilters:Filters={categories:[],min:'',max:'',delivery:0,serviceTypes:[],sources:[]}
const interpolate=(value:string,vars:Record<string,string|number>)=>Object.entries(vars).reduce((text,[key,replacement])=>text.replace(`{${key}}`,String(replacement)),value)
const copy={ka:{search:'მომსახურების ძიება',placeholder:'მოძებნე სახელით, კატეგორიით ან მიმწოდებლით',clearSearch:'ძიების გასუფთავება',invalidPrice:'მაქსიმალური ფასი უნდა იყოს მინიმუმის ტოლი ან მეტი.',negativePrice:'ფასი არ შეიძლება იყოს უარყოფითი.',active:'აქტიური ფილტრები',clearAll:'ყველას გასუფთავება',back:'ყველა კატეგორია',related:'დაკავშირებული კატეგორიები',type:'ტიპი',source:'წყარო'},en:{search:'Search services',placeholder:'Search by service, category, or provider',clearSearch:'Clear search',invalidPrice:'Maximum price must be equal to or greater than minimum.',negativePrice:'Price cannot be negative.',active:'Active filters',clearAll:'Clear all',back:'All categories',related:'Related categories',type:'Type',source:'Source'}} as const
const related:Record<string,string[]>={marketing:['advertising','social','seo'],web:['design','seo','automation'],design:['web','social','video'],social:['marketing','advertising','video'],seo:['web','marketing','advertising'],advertising:['marketing','social','video'],video:['social','advertising','design'],automation:['ai','web','consulting'],ai:['automation','consulting','marketing'],consulting:['marketing','automation','ai']}
const publicServices=()=>catalogServices.filter(isServicePublic)
const parseList=(params:URLSearchParams,key:string)=>params.getAll(key).flatMap(x=>x.split(',')).filter(Boolean)
function initialState(category?:string){const p=new URLSearchParams(window.location.search);return {filters:{categories:category?[category]:parseList(p,'category'),min:p.get('min')??'',max:p.get('max')??'',delivery:Number(p.get('delivery')??0),serviceTypes:parseList(p,'type'),sources:parseList(p,'source')} satisfies Filters,sort:(['recommended','priceLow','priceHigh','newest'].includes(p.get('sort')??'')?p.get('sort'):'recommended') as SortKey,query:p.get('q')??p.get('search')??''}}
function priceError(filters:Filters,locale:Locale){const min=filters.min===''?undefined:Number(filters.min),max=filters.max===''?undefined:Number(filters.max);if((min!==undefined&&min<0)||(max!==undefined&&max<0))return copy[locale].negativePrice;if(min!==undefined&&max!==undefined&&max<min)return copy[locale].invalidPrice;return ''}
function FavoriteButton({locale,serviceId}:{locale:Locale;serviceId:string}){const active=useFavorites().includes(serviceId),t=dictionary[locale];return <button className="favorite" type="button" aria-pressed={active} aria-label={active?t.home.removeFavorite:t.home.addFavorite} onClick={()=>toggleFavorite(serviceId)}><Heart fill={active?'currentColor':'none'} aria-hidden="true"/></button>}
function ServiceListItem({service,locale}:{service:Service;locale:Locale}){const t=dictionary[locale];return <article className="service-list-item"><a className="list-media" href={localePath(locale,`/services/${service.slug}`)}><ServiceMedia service={service}/></a><div className="list-main"><div className="inline-badges"><ServiceSourceBadge service={service} locale={locale} className="list-source-badge"/></div><a className="service-title" href={localePath(locale,`/services/${service.slug}`)}>{service.title[locale]}</a><p>{service.description[locale]}</p><div className="service-facts"><span>{t.catalog[service.serviceType]}</span>{service.serviceType!=='monthly'&&<span><Clock3/>{interpolate(t.catalog.deliveryDays,{count:service.deliveryDays})}</span>}</div></div><div className="list-aside"><FavoriteButton locale={locale} serviceId={service.id}/>{service.reviews>0&&<span className="rating"><Star fill="currentColor"/> {service.rating} <small>({service.reviews})</small></span>}<ServicePrice service={service} locale={locale}/><a className="compact-button" href={localePath(locale,`/services/${service.slug}`)}>{t.catalog.viewDetails}</a></div></article>}
function FilterGroup({legend,children}:{legend:string;children:React.ReactNode}){return <fieldset className="filter-group"><legend>{legend}</legend>{children}</fieldset>}
function Check({checked,onChange,label,meta}:{checked:boolean;onChange:()=>void;label:string;meta?:number}){return <label className="filter-option"><input type="checkbox" checked={checked} onChange={onChange}/><span>{label}</span>{meta!==undefined&&<small>{meta}</small>}</label>}
type FilterProps={locale:Locale;value:Filters;lockedCategory?:string;onChange:(next:Filters)=>void;onClear:()=>void;onApply?:()=>void;resultCount?:number}
function MarketplaceFilters({locale,value,lockedCategory,onChange,onClear,onApply,resultCount}:FilterProps){const t=dictionary[locale].catalog,error=priceError(value,locale),counts=useMemo(()=>Object.fromEntries(categories.map(c=>[c.id,publicServices().filter(s=>s.category===c.id).length])),[]);const updateList=(key:'categories'|'serviceTypes'|'sources',item:string)=>onChange({...value,[key]:value[key].includes(item)?value[key].filter(x=>x!==item):[...value[key],item]});return <div className="marketplace-filters">
 {!lockedCategory&&<FilterGroup legend={t.category}>{categories.map(c=><Check key={c.id} label={c.name[locale]} meta={counts[c.id]} checked={value.categories.includes(c.id)} onChange={()=>updateList('categories',c.id)}/>)}</FilterGroup>}
 <FilterGroup legend={`${t.price} (GEL)`}><div className="price-inputs"><label>{t.min}<span><input aria-label={t.min} type="number" min="0" inputMode="numeric" value={value.min} placeholder="0" onChange={e=>onChange({...value,min:e.target.value})}/><b>₾</b></span></label><i>—</i><label>{t.max}<span><input aria-label={t.max} type="number" min="0" inputMode="numeric" value={value.max} placeholder="∞" onChange={e=>onChange({...value,max:e.target.value})}/><b>₾</b></span></label></div>{error&&<p className="filter-error" role="alert">{error}</p>}</FilterGroup>
 <FilterGroup legend={t.serviceType}>{(['oneTime','monthly','consultation'] as const).map(key=><Check key={key} label={t[key]} checked={value.serviceTypes.includes(key)} onChange={()=>updateList('serviceTypes',key)}/>)}</FilterGroup>
 <FilterGroup legend={t.serviceProvider}><Check label={t.sourceDigitalStep} checked={value.sources.includes('DIGITAL_STEP')} onChange={()=>updateList('sources','DIGITAL_STEP')}/><Check label={t.sourceVerified} checked={value.sources.includes('VERIFIED_PROVIDER')} onChange={()=>updateList('sources','VERIFIED_PROVIDER')}/></FilterGroup>
 <FilterGroup legend={t.delivery}>{[[0,t.anyDelivery],[1,t.dayOne],[3,t.dayThree],[7,t.daySeven]].map(([days,label])=><label className="filter-option" key={days}><input type="radio" name={onApply?'mobile-delivery':'desktop-delivery'} checked={value.delivery===days} onChange={()=>onChange({...value,delivery:Number(days)})}/><span>{label}</span></label>)}</FilterGroup>
 <div className="filter-actions"><button type="button" className="clear-button" onClick={onClear}>{t.clear}</button>{onApply&&<button type="button" className="apply-button" disabled={Boolean(error)} onClick={onApply}>{t.showResults} ({resultCount??0})</button>}</div>
 </div>}
function SortControl({locale,value,onChange}:{locale:Locale;value:SortKey;onChange:(v:SortKey)=>void}){const t=dictionary[locale].catalog;return <label className="sort-control"><span>{t.sort}</span><div><select aria-label={t.sort} value={value} onChange={e=>onChange(e.target.value as SortKey)}>{(['recommended','newest','priceLow','priceHigh'] as const).map(k=><option key={k} value={k}>{t[k]}</option>)}</select><ChevronDown/></div></label>}
function filterCatalog(filters:Filters,query:string){const min=Number(filters.min),max=Number(filters.max);return publicServices().filter(s=>{const category=categories.find(c=>c.id===s.category);const searchable=`${s.title.ka} ${s.title.en} ${s.description.ka} ${s.description.en} ${s.provider} ${category?.name.ka??''} ${category?.name.en??''} ${s.serviceSource==='DIGITAL_STEP'?'Digital Step':'Verified Provider'}`.toLocaleLowerCase();const deliveryOk=!filters.delivery||s.serviceType==='monthly'||s.deliveryDays<=filters.delivery;const priceOk=(filters.min===''||s.price>=min)&&(filters.max===''||s.price<=max);return (!filters.categories.length||filters.categories.includes(s.category))&&(!filters.sources.length||filters.sources.includes(s.serviceSource))&&(!filters.serviceTypes.length||filters.serviceTypes.includes(s.serviceType))&&deliveryOk&&priceOk&&(!query.trim()||searchable.includes(query.trim().toLocaleLowerCase()))})}
export function Catalog({locale,categorySlug,searchQuery}: {locale:Locale;categorySlug?:string;searchQuery?:string}){const t=dictionary[locale].catalog,c=copy[locale],initialCategory=categories.find(item=>item.id===categorySlug),unknownCategory=Boolean(categorySlug&&!initialCategory),initial=initialState(initialCategory?.id);const initialValidPrice=priceError(initial.filters,locale)?{min:'',max:''}:{min:initial.filters.min,max:initial.filters.max};const [filters,setFilters]=useState(initial.filters),[validPrice,setValidPrice]=useState(initialValidPrice),[draft,setDraft]=useState(initial.filters),[sort,setSort]=useState(initial.sort),[view,setView]=useState<View>('grid'),[drawer,setDrawer]=useState(false),[query,setQuery]=useState(searchQuery??initial.query),drawerTitle=useId();
 const effectiveFilters=useMemo(()=>({...filters,...validPrice,categories:initialCategory?[initialCategory.id]:filters.categories}),[filters,validPrice,initialCategory]);
 const results=useMemo(()=>filterCatalog(effectiveFilters,query).map((service,index)=>({service,index})).sort((a,b)=>{const d=sort==='priceLow'?a.service.price-b.service.price:sort==='priceHigh'?b.service.price-a.service.price:sort==='newest'?b.service.createdOrder-a.service.createdOrder:sort==='recommended'?(Number(Boolean(b.service.isFeatured))-Number(Boolean(a.service.isFeatured))||Number(Boolean(b.service.isPopular))-Number(Boolean(a.service.isPopular))||Number(b.service.serviceSource==='DIGITAL_STEP')-Number(a.service.serviceSource==='DIGITAL_STEP')):0;return d||a.index-b.index}).map(x=>x.service),[effectiveFilters,query,sort]);
 const draftCount=useMemo(()=>{const validDraft=priceError(draft,locale)?{...draft,...validPrice}:draft;return filterCatalog({...validDraft,categories:initialCategory?[initialCategory.id]:validDraft.categories},query).length},[draft,validPrice,initialCategory,locale,query]);
 const changeFilters=(next:Filters)=>{setFilters(next);if(!priceError(next,locale))setValidPrice({min:next.min,max:next.max})};
 useEffect(()=>{const p=new URLSearchParams();if(query)p.set('q',query);filters.categories.forEach(x=>!initialCategory&&p.append('category',x));filters.serviceTypes.forEach(x=>p.append('type',x));filters.sources.forEach(x=>p.append('source',x));if(validPrice.min)p.set('min',validPrice.min);if(validPrice.max)p.set('max',validPrice.max);if(filters.delivery)p.set('delivery',String(filters.delivery));if(sort!=='recommended')p.set('sort',sort);window.history.replaceState(null,'',`${window.location.pathname}${p.size?`?${p}`:''}`)},[filters,validPrice,sort,query,initialCategory]);
 useEffect(()=>{if(!drawer)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(false)};document.addEventListener('keydown',close);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=old}},[drawer]);
 const clear=()=>changeFilters({...emptyFilters,categories:initialCategory?[initialCategory.id]:[]});const clearDraft=()=>setDraft({...emptyFilters,categories:initialCategory?[initialCategory.id]:[]});const submit=(e:FormEvent)=>{e.preventDefault();setQuery(query.trim())};
 if(unknownCategory)return <div className="catalog-empty category-not-found"><span><SearchX/></span><h1>{locale==='ka'?'კატეგორია ვერ მოიძებნა':'Category not found'}</h1><p>{locale==='ka'?'შეამოწმე მისამართი ან დაბრუნდი მარკეტპლეისზე.':'Check the address or return to the marketplace.'}</p><a className="empty-state-action" href={localePath(locale,'/marketplace')}>{t.allCategories}</a></div>;
 const chips:[string,string,()=>void][]=[];if(!initialCategory)filters.categories.forEach(id=>chips.push([`category-${id}`,categories.find(x=>x.id===id)?.name[locale]??id,()=>changeFilters({...filters,categories:filters.categories.filter(x=>x!==id)})]));filters.serviceTypes.forEach(type=>chips.push([`type-${type}`,t[type as 'oneTime'],()=>changeFilters({...filters,serviceTypes:filters.serviceTypes.filter(x=>x!==type)})]));filters.sources.forEach(source=>chips.push([`source-${source}`,source==='DIGITAL_STEP'?t.sourceDigitalStep:t.sourceVerified,()=>changeFilters({...filters,sources:filters.sources.filter(x=>x!==source)})]));if(filters.min||filters.max)chips.push(['price',`${filters.min||'0'}–${filters.max||'∞'} ₾`,()=>changeFilters({...filters,min:'',max:''})]);if(filters.delivery)chips.push(['delivery',interpolate(t.deliveryDays,{count:filters.delivery}),()=>changeFilters({...filters,delivery:0})]);
 return <div className="catalog-page"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href={localePath(locale,'/')}>{t.home}</a><span>/</span>{initialCategory&&<><a href={localePath(locale,'/marketplace')}>{t.marketplace}</a><span>/</span></>}<strong>{initialCategory?.name[locale]??t.marketplace}</strong></nav>
  <header className={`catalog-header ${initialCategory?'category-header':''}`}>{initialCategory&&<span className="catalog-category-icon"><MarketplaceIcon name={initialCategory.icon}/></span>}<div>{initialCategory&&<a className="category-back" href={localePath(locale,'/marketplace')}>← {c.back}</a>}<p className="catalog-eyebrow">{t.marketplace}</p><h1>{initialCategory?.name[locale]??t.marketplace}</h1><p>{initialCategory?.description[locale]??t.subtitle}</p><strong>{interpolate(t.servicesFound,{count:results.length})}</strong></div></header>
  <form className="catalog-search" role="search" onSubmit={submit}><Search/><label className="visually-hidden" htmlFor="catalog-query">{c.search}</label><input id="catalog-query" value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.placeholder}/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label={c.clearSearch}><X/></button>}</form>
  {query&&<div className="search-feedback"><strong>{interpolate(t.searchTitle,{query})}</strong><span>{interpolate(t.resultsFound,{count:results.length})}</span><button onClick={()=>setQuery('')}>{c.clearSearch}</button></div>}
  {initialCategory&&<section className="related-categories"><h2>{c.related}</h2><div>{(related[initialCategory.id]??[]).map(id=>{const item=categories.find(x=>x.id===id);return item&&<a key={id} href={localePath(locale,`/categories/${id}`)}><MarketplaceIcon name={item.icon}/>{item.name[locale]}</a>})}</div></section>}
  <div className="catalog-layout"><aside className="filter-sidebar" aria-label={t.filters}><MarketplaceFilters locale={locale} value={filters} lockedCategory={initialCategory?.id} onChange={changeFilters} onClear={clear}/></aside><section className="catalog-results"><div className="results-toolbar"><p>{interpolate(t.servicesFound,{count:results.length})}</p><div className="catalog-controls"><button className="mobile-filter-button" type="button" aria-expanded={drawer} onClick={()=>{setDraft(filters);setDrawer(true)}}><SlidersHorizontal/>{t.filters}{chips.length>0&&<b>{chips.length}</b>}</button><SortControl locale={locale} value={sort} onChange={setSort}/><div className="view-switch" role="group" aria-label={`${t.grid} / ${t.list}`}><button type="button" aria-label={t.grid} aria-pressed={view==='grid'} onClick={()=>setView('grid')}><Grid2X2/></button><button type="button" aria-label={t.list} aria-pressed={view==='list'} onClick={()=>setView('list')}><List/></button></div></div></div>
  {chips.length>0&&<div className="active-filters" aria-label={c.active}>{chips.map(([key,label,remove])=><button key={key} onClick={remove}>{label}<X/></button>)}<button className="clear-all" onClick={clear}>{c.clearAll}</button></div>}
  {results.length===0?<div className="catalog-empty"><span><SearchX/></span><h2>{t.noResults}</h2><p>{initialCategory&&!query&&chips.length===0?(locale==='ka'?'ამ კატეგორიაში მომსახურებები ჯერ არ არის დამატებული.':'No services have been added to this category yet.'):t.noResultsText}</p><div className="empty-actions"><button type="button" onClick={clear}>{t.clear}</button><a href={localePath(locale,'/marketplace')}>{t.allServices}</a></div></div>:view==='grid'?<div className="catalog-grid">{results.map(s=><ServiceCard key={s.id} service={s} locale={locale}/>)}</div>:<div className="catalog-list">{results.map(s=><ServiceListItem key={s.id} service={s} locale={locale}/>)}</div>}</section></div>
  {drawer&&<div className="filter-drawer-layer" onMouseDown={e=>{if(e.target===e.currentTarget)setDrawer(false)}}><section className="filter-drawer" role="dialog" aria-modal="true" aria-labelledby={drawerTitle}><header><h2 id={drawerTitle}>{t.filters}</h2><button type="button" aria-label={t.close} onClick={()=>setDrawer(false)}><X/></button></header><div className="drawer-scroll"><MarketplaceFilters locale={locale} value={draft} lockedCategory={initialCategory?.id} onChange={setDraft} onClear={clearDraft} resultCount={draftCount} onApply={()=>{changeFilters(draft);setDrawer(false)}}/></div></section></div>}
 </div>}
export function CatalogSkeleton({category=false}:{category?:boolean}){return <div className="catalog-skeleton" aria-hidden="true">{category&&<div className="skeleton category-header-skeleton"/>}<div className="skeleton catalog-title-skeleton"/><div className="catalog-layout"><div className="skeleton filter-skeleton"/><div className="skeleton-catalog-grid">{Array.from({length:6},(_,i)=><div className="skeleton card-skeleton" key={i}/>)}</div></div></div>}
