import { useEffect, useId, useRef, useState } from 'react'
import { Check, ChevronDown, Heart, Play, Star, X } from 'lucide-react'
import type { Locale } from '../../i18n'
import { localePath } from '../../i18n'
import type { GalleryItem, PackageTier, Provider, Review, ServicePackage } from '../../data/serviceDetails'

const labels={
 ka:{basic:'საბაზისო',standard:'სტანდარტი',premium:'პრემიუმი',packages:'პაკეტები',delivery:'მიწოდების ვადა',days:'დღე',revisions:'შესწორებები',order:'შეკვეთა',consult:'კონსულტაცია',selected:'არჩეული პაკეტი',viewImage:'სურათის ნახვა',provider:'მომსახურების მიმწოდებელი',viewProfile:'პროფილის ნახვა',reviews:'შეფასებები',close:'დახურვა'},
 en:{basic:'Basic',standard:'Standard',premium:'Premium',packages:'Packages',delivery:'Delivery Time',days:'days',revisions:'Revisions',order:'Order Service',consult:'Request Consultation',selected:'Selected package',viewImage:'View image',provider:'Service Provider',viewProfile:'View Profile',reviews:'Reviews',close:'Close'},
} as const
const tierLabel=(locale:Locale,tier:PackageTier)=>labels[locale][tier]
export function ServiceGallery({items,locale}:{items:GalleryItem[];locale:Locale}) { const [selected,setSelected]=useState(0); const item=items[selected]; return <section className="detail-gallery" aria-label={labels[locale].viewImage}><div className={`gallery-main preview-${item.tone.split(' ')[0]} ${item.tone.replaceAll(' ','-')}`} role="img" aria-label={item.label[locale]}>{item.video&&<span className="play"><Play fill="currentColor"/></span>}<div className="gallery-art"><i/><i/><i/></div><strong>{item.label[locale]}</strong></div><div className="gallery-thumbs" role="tablist">{items.map((galleryItem,index)=><button key={galleryItem.id} type="button" role="tab" aria-selected={selected===index} aria-label={`${labels[locale].viewImage}: ${galleryItem.label[locale]}`} onClick={()=>setSelected(index)}><span className={`preview-${galleryItem.tone.split(' ')[0]}`}>{galleryItem.video&&<Play/>}</span><small>{index+1}</small></button>)}</div></section> }
export function PackageSelector({packages,locale,selected,onSelect,onAction}:{packages:ServicePackage[];locale:Locale;selected:PackageTier;onSelect:(tier:PackageTier)=>void;onAction:(kind:'order'|'consult')=>void}) { const pack=packages.find(p=>p.id===selected)??packages[0]; return <section className="purchase-card" aria-labelledby="packages-title"><h2 id="packages-title">{labels[locale].packages}</h2><div className="package-tabs" role="tablist" aria-label={labels[locale].packages}>{packages.map(item=><button type="button" role="tab" aria-selected={item.id===selected} key={item.id} onClick={()=>onSelect(item.id)}><span>{tierLabel(locale,item.id)}</span>{item.id===selected&&<small>{labels[locale].selected}</small>}</button>)}</div><div className="package-content"><div className="package-price"><strong>{pack.price}₾</strong><span>{tierLabel(locale,pack.id)}</span></div><p>{pack.description[locale]}</p><dl><div><dt>{labels[locale].delivery}</dt><dd>{pack.deliveryDays} {labels[locale].days}</dd></div><div><dt>{labels[locale].revisions}</dt><dd>{pack.revisions}</dd></div></dl><ul>{pack.features.map(feature=><li key={feature.en}><Check/>{feature[locale]}</li>)}</ul><button className="primary-action" type="button" onClick={()=>onAction('order')}>{labels[locale].order}</button><button className="secondary-action" type="button" onClick={()=>onAction('consult')}>{labels[locale].consult}</button></div></section> }
export function ProviderCard({provider,locale}:{provider:Provider;locale:Locale}) { return <section className="provider-card"><small>{labels[locale].provider}</small><div className="provider-identity"><span>{provider.name.split(' ').map(word=>word[0]).slice(0,2)}</span><div><strong>{provider.name}</strong><p>{provider.type[locale]}</p></div></div><div className="provider-mini-meta"><span><Star fill="currentColor"/> 4.9</span><span>{provider.responseTime[locale]}</span></div><a className="secondary-action" href={localePath(locale,`/providers/${provider.slug}`)}>{labels[locale].viewProfile}</a></section> }
export function RatingSummary({rating,reviews,locale}:{rating:number;reviews:Review[];locale:Locale}) { const counts=[5,4,3,2,1].map(star=>reviews.filter(review=>review.rating===star).length); return <div className="rating-summary" aria-label={`${rating}, ${reviews.length} ${labels[locale].reviews}`}><div><strong>{rating.toFixed(1)}</strong><span aria-hidden="true">★★★★★</span><small>{reviews.length} {labels[locale].reviews}</small></div><ol>{counts.map((count,index)=>{const star=5-index;const percent=reviews.length?Math.round(count/reviews.length*100):0;return <li key={star} aria-label={`${star} stars: ${percent}%`}><span>{star} ★</span><i><b style={{width:`${percent}%`}}/></i><em>{percent}%</em></li>})}</ol></div> }
export function ReviewCard({review,locale}:{review:Review;locale:Locale}) { const formatted=new Intl.DateTimeFormat(locale==='ka'?'ka-GE':'en-US',{year:'numeric',month:'short',day:'numeric'}).format(new Date(review.date)); return <article className="review-card"><header><span>{review.author[0]}</span><div><strong>{review.author}</strong><small><b>★ {review.rating}</b> · {formatted} · {tierLabel(locale,review.package)}</small></div></header><p>{review.text[locale]}</p></article> }
export function FaqList({items,locale}:{items:{id:string;question:Record<Locale,string>;answer:Record<Locale,string>}[];locale:Locale}) { const [open,setOpen]=useState<string|null>(items[0]?.id??null); return <div className="faq-list">{items.map(item=>{const id=`faq-${item.id}`;const active=open===item.id;return <article key={item.id}><h3><button type="button" aria-expanded={active} aria-controls={id} onClick={()=>setOpen(active?null:item.id)}>{item.question[locale]}<ChevronDown/></button></h3><div id={id} hidden={!active}><p>{item.answer[locale]}</p></div></article>})}</div> }
export function InfoDialog({open,onClose,title,message}:{open:boolean;onClose:()=>void;title:string;message:string}) { const titleId=useId(); const closeRef=useRef<HTMLButtonElement>(null); useEffect(()=>{if(open) closeRef.current?.focus()},[open]); if(!open)return null; return <div className="dialog-layer" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="info-dialog" role="dialog" aria-modal="true" aria-labelledby={titleId} onKeyDown={event=>{if(event.key==='Escape')onClose()}}><button ref={closeRef} className="dialog-close" aria-label="Close" onClick={onClose}><X/></button><span className="dialog-mark">DS</span><h2 id={titleId}>{title}</h2><p>{message}</p><button className="primary-action" onClick={onClose}>OK</button></div></div> }
export function FavoriteButton({locale}:{locale:Locale}) { const [active,setActive]=useState(false); return <button className="detail-favorite" type="button" aria-pressed={active} aria-label={locale==='ka'?'რჩეულებში დამატება':'Add to favorites'} onClick={()=>setActive(value=>!value)}><Heart fill={active?'currentColor':'none'}/></button> }
