import { useEffect, useId, useRef, useState } from 'react'
import { BadgeCheck, Check, ChevronDown, Heart, Play, Sparkles, Star, X } from 'lucide-react'
import type { Locale } from '../../i18n'
import { localePath } from '../../i18n'
import type { GalleryItem, PackageTier, Provider, Review, ServicePackage } from '../../data/serviceDetails'
import type { ServiceType } from '../../data/marketplace'
import { toggleFavorite, useFavorites } from '../../lib/favorites'

const labels={
 ka:{packages:'პაკეტები',delivery:'მიწოდება',period:'მომსახურების პერიოდი',days:'დღე',revisions:'შესწორება',order:'შეკვეთა',selected:'არჩეული',viewImage:'მედიის ნახვა',provider:'მომსახურების მიმწოდებელი',verified:'დადასტურებული პროვაიდერი',viewProfile:'პროფილის ნახვა',close:'დახურვა',fallback:'Digital Step სერვისი',month:'/ თვე'},
 en:{packages:'Packages',delivery:'Delivery',period:'Service period',days:'days',revisions:'revisions',order:'Order Service',selected:'Selected',viewImage:'View media',provider:'Service provider',verified:'Verified Provider',viewProfile:'View profile',close:'Close',fallback:'Digital Step Service',month:'/ month'},
} as const
const optimize=(url:string,width:number)=>url.includes('/upload/')?url.replace('/upload/',`/upload/f_auto,q_auto,w_${width},c_limit/`):url
const poster=(url:string)=>url.includes('/upload/')?url.replace('/upload/','/upload/so_0,f_jpg,q_auto,w_240,h_150,c_fill/').replace(/\.[^.]+$/,'.jpg'):''

export function ServiceGallery({items,locale,title}:{items:GalleryItem[];locale:Locale;title:string}) {
 const [selected,setSelected]=useState(0),[viewer,setViewer]=useState(false); const closeRef=useRef<HTMLButtonElement>(null)
 useEffect(()=>{if(!viewer)return;closeRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setViewer(false)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[viewer])
 const item=items[selected]
 const fallback=<div className="gallery-main gallery-fallback" role="img" aria-label={`${title} — Digital Step`}><Sparkles/><strong>Digital Step</strong><span>{labels[locale].fallback}</span></div>
 return <section className="detail-gallery" aria-label={labels[locale].viewImage}>
  {!item?fallback:item.url?(item.video?<video className="gallery-main media-player" src={item.url} poster={poster(item.url)||undefined} controls preload="metadata" aria-label={`${title} — ${item.label[locale]}`}/>:<button className="gallery-image-button" type="button" onClick={()=>setViewer(true)} aria-label={`${labels[locale].viewImage}: ${title}`}><img className="gallery-main media-player" src={optimize(item.url,1400)} alt={`${title} — Digital Step`} fetchPriority="high"/></button>):fallback}
  {items.length>1&&<div className="gallery-thumbs" role="tablist" aria-label={labels[locale].viewImage}>{items.map((galleryItem,index)=><button key={galleryItem.id} type="button" role="tab" aria-selected={selected===index} aria-label={`${labels[locale].viewImage}: ${galleryItem.label[locale]}`} onClick={()=>setSelected(index)}>{galleryItem.url&&galleryItem.video?<span className="media-video-thumb" style={poster(galleryItem.url)?{backgroundImage:`url(${poster(galleryItem.url)})`}:undefined}><Play fill="currentColor"/></span>:galleryItem.url?<img src={optimize(galleryItem.url,220)} alt="" loading="lazy"/>:<span className="media-video-thumb"><Play/></span>}</button>)}</div>}
  {viewer&&item?.url&&!item.video&&<div className="image-viewer" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setViewer(false)}}><div role="dialog" aria-modal="true" aria-label={`${labels[locale].viewImage}: ${title}`}><button ref={closeRef} type="button" aria-label={labels[locale].close} onClick={()=>setViewer(false)}><X/></button><img src={optimize(item.url,2000)} alt={`${title} — Digital Step`}/></div></div>}
 </section>
}

export function PackageSelector({packages,locale,selected,onSelect,onOrder,serviceType}:{packages:ServicePackage[];locale:Locale;selected:PackageTier;onSelect:(tier:PackageTier)=>void;onOrder:()=>void;serviceType:ServiceType}) {
 const pack=packages.find(p=>p.id===selected)??packages[0]; if(!pack)return null; const monthly=serviceType==='monthly'
 return <section className={`purchase-card ${packages.length===1?'single-package':''}`} aria-labelledby="packages-title"><h2 id="packages-title">{packages.length===1?(pack.name?.[locale]||labels[locale].packages):labels[locale].packages}</h2>
  {packages.length>1&&<div className="package-tabs" role="tablist" aria-label={labels[locale].packages}>{packages.map(item=><button type="button" role="tab" aria-selected={item.id===selected} key={item.id} onClick={()=>onSelect(item.id)}><span>{item.name?.[locale]||item.id}</span>{item.id===selected&&<small>{labels[locale].selected}</small>}</button>)}</div>}
  <div className="package-content"><div className="package-price"><strong>{pack.price.toLocaleString(locale==='ka'?'ka-GE':'en-US')}₾ {monthly&&<small>{labels[locale].month}</small>}</strong>{packages.length>1&&<span>{pack.name?.[locale]||pack.id}</span>}</div>{pack.description[locale]&&<p>{pack.description[locale]}</p>}<dl><div><dt>{monthly?labels[locale].period:labels[locale].delivery}</dt><dd>{pack.deliveryDays} {labels[locale].days}</dd></div>{pack.revisions>0&&<div><dt>{labels[locale].revisions}</dt><dd>{pack.revisions}</dd></div>}</dl>{pack.features.length>0&&<ul>{pack.features.map((feature,index)=><li key={`${feature.en}-${index}`}><Check/>{feature[locale]||feature.ka}</li>)}</ul>}<button className="primary-action" type="button" onClick={onOrder}>{labels[locale].order}</button></div>
 </section>
}
export function ProviderCard({provider,locale}:{provider:Provider;locale:Locale}) { return <section className="provider-card"><small>{labels[locale].provider}</small><div className="provider-identity"><span>{provider.name.split(' ').map(word=>word[0]).slice(0,2)}</span><div><strong>{provider.name}</strong><p><BadgeCheck/> {labels[locale].verified}</p></div></div><a className="secondary-action" href={localePath(locale,`/providers/${provider.slug}`)}>{labels[locale].viewProfile}</a></section> }
export function DigitalStepCard({locale}:{locale:Locale}) {return <section className="provider-card official-trust"><Sparkles/><div><strong>Digital Step</strong><p>{locale==='ka'?'ოფიციალური Digital Step სერვისი':'Official Digital Step service'}</p></div><ul><li><Check/>{locale==='ka'?'ერთიანი გუნდი':'One coordinated team'}</li><li><Check/>{locale==='ka'?'ორგანიზებული პროცესი':'Organized process'}</li><li><Check/>{locale==='ka'?'მხარდაჭერა':'Support'}</li></ul></section>}
export function FaqList({items,locale}:{items:{id:string;question:Record<Locale,string>;answer:Record<Locale,string>}[];locale:Locale}) { const [open,setOpen]=useState<string|null>(null); return <div className="faq-list">{items.map(item=>{const id=`faq-${item.id}`;const active=open===item.id;return <article key={item.id}><h3><button type="button" aria-expanded={active} aria-controls={id} onClick={()=>setOpen(active?null:item.id)}>{item.question[locale]||item.question.ka}<ChevronDown/></button></h3><div id={id} hidden={!active}><p>{item.answer[locale]||item.answer.ka}</p></div></article>})}</div> }
export function FavoriteButton({locale,serviceId}:{locale:Locale;serviceId:string}) { const active=useFavorites().includes(serviceId); return <button className="detail-favorite" type="button" aria-pressed={active} aria-label={active?(locale==='ka'?'რჩეულებიდან წაშლა':'Remove from favorites'):(locale==='ka'?'რჩეულებში დამატება':'Add to favorites')} onClick={()=>toggleFavorite(serviceId)}><Heart fill={active?'currentColor':'none'}/></button> }

export function RatingSummary({rating,reviews,locale}:{rating:number;reviews:Review[];locale:Locale}) { const counts=[5,4,3,2,1].map(star=>reviews.filter(review=>review.rating===star).length); return <div className="rating-summary" aria-label={`${rating}, ${reviews.length}`}><div><strong>{rating.toFixed(1)}</strong><span aria-hidden="true">★★★★★</span><small>{reviews.length}</small></div><ol>{counts.map((count,index)=>{const star=5-index,percent=reviews.length?Math.round(count/reviews.length*100):0;return <li key={star}><span>{star} ★</span><i><b style={{width:`${percent}%`}}/></i><em>{percent}%</em></li>})}</ol></div> }
export function ReviewCard({review,locale}:{review:Review;locale:Locale}) { const date=new Intl.DateTimeFormat(locale==='ka'?'ka-GE':'en-US',{year:'numeric',month:'short',day:'numeric'}).format(new Date(review.date));return <article className="review-card"><header><span>{review.author[0]}</span><div><strong>{review.author}</strong><small><b><Star/> {review.rating}</b> · {date}</small></div></header><p>{review.text[locale]}</p></article> }
export function InfoDialog({open,onClose,title,message}:{open:boolean;onClose:()=>void;title:string;message:string}) {const id=useId(),ref=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;ref.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[open,onClose]);if(!open)return null;return <div className="dialog-layer" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="info-dialog" role="dialog" aria-modal="true" aria-labelledby={id}><button ref={ref} className="dialog-close" aria-label="Close" onClick={onClose}><X/></button><h2 id={id}>{title}</h2><p>{message}</p><button className="primary-action" onClick={onClose}>OK</button></div></div>}
