import{Bot,LayoutDashboard,ListOrdered,LogOut,PackageCheck,ShieldCheck,UsersRound,WalletCards}from'lucide-react'
import{useState,type ReactNode}from'react'
import{useAuth}from'../../auth/AuthContext'
import{localePath,type Locale}from'../../i18n'
import{Logo}from'../Logo'
import { NotificationCenter } from '../NotificationCenter'
const adminCopy={ka:{administration:'ადმინისტრირება',dashboard:'ადმინისტრატორის პანელი',overview:'მიმოხილვა',users:'მომხმარებლები',providers:'პროვაიდერები',services:'სერვისები',orders:'შეკვეთები',subscriptions:'გამოწერები',usage:'AI გამოყენება',back:'მარკეტპლეისზე დაბრუნება',logout:'გასვლა'},en:{administration:'Administration',dashboard:'Admin Dashboard',overview:'Overview',users:'Users',providers:'Providers',services:'Services',orders:'Orders',subscriptions:'Subscriptions',usage:'AI Usage',back:'Back to Marketplace',logout:'Sign Out'}}as const
const links=[['overview','/admin',LayoutDashboard],['users','/admin/users',UsersRound],['providers','/admin/providers',ShieldCheck],['services','/admin/services',PackageCheck],['orders','/admin/orders',ListOrdered],['subscriptions','/admin/subscriptions',WalletCards],['usage','/admin/ai-usage',Bot]]as const
export function AdminLayout({locale,children}:{locale:Locale;children:ReactNode}){const c=adminCopy[locale],{user,logout}=useAuth(),[busy,setBusy]=useState(false),path=window.location.pathname;if(!user)return null;const link=([key,href,Icon]:(typeof links)[number])=>{const target=localePath(locale,href),active=key==='overview'?path===target:path.startsWith(target);return <a key={key} href={target} className={active?'active':undefined} aria-current={active?'page':undefined}><Icon aria-hidden="true"/><span>{c[key]}</span></a>};return <div className="dashboard-shell admin-shell"><aside className="dashboard-sidebar"><Logo href={localePath(locale,'/admin')}/><nav aria-label={c.administration}>{links.map(link)}</nav><a className="marketplace-return" href={localePath(locale,'/marketplace')}><LogOut aria-hidden="true"/>{c.back}</a><button className="marketplace-return" type="button" disabled={busy} onClick={async()=>{setBusy(true);await logout();window.location.assign(localePath(locale,'/login'))}}><LogOut aria-hidden="true"/>{c.logout}</button></aside><div className="dashboard-area"><header className="dashboard-header"><div className="dashboard-mobile-brand"><Logo href={localePath(locale,'/admin')}/></div><strong>{c.administration}</strong><NotificationCenter locale={locale}/><a className="language-switch" href={localePath(locale==='ka'?'en':'ka',path)}>{locale==='ka'?'English':'ქართული'}</a><div className="dashboard-account"><span>{user.firstName[0]}{user.lastName[0]}</span><div><strong>{user.firstName} {user.lastName}</strong><small>{c.administration}</small></div></div></header><main className="dashboard-content">{children}</main><nav className="dashboard-mobile-nav admin-mobile-nav" aria-label={c.administration}>{links.map(link)}</nav></div></div>}
