import {useEffect,useMemo,useState,type FormEvent,type ReactNode} from 'react'
import {adminApi,deleteServiceMedia,uploadServiceMedia,type ServiceMedia,type ServicePackage,type ServicePayload,type ServiceStatus,type ServiceType} from '../../lib/api/admin'
import {categories} from '../../data/marketplace'
import {localePath,type Locale} from '../../i18n'
import {normalizeServicePackages} from '../../../shared/servicePackages'

const uid=()=>crypto.randomUUID()
const blankPackage=():ServicePackage=>({key:`package-${Date.now()}`,nameKa:'',nameEn:'',descriptionKa:'',descriptionEn:'',priceMinor:0,deliveryDays:1,revisions:1,features:[]})
const initial:ServicePayload={titleKa:'',titleEn:'',descriptionKa:'',descriptionEn:'',fullDescriptionKa:'',fullDescriptionEn:'',category:'marketing',serviceType:'ONE_TIME',priceMinor:0,deliveryDays:1,status:'DRAFT',isFeatured:false,isPopular:false,packages:[blankPackage()],includedItems:[],processSteps:[],faqs:[],seoTitleKa:null,seoTitleEn:null,seoDescriptionKa:null,seoDescriptionEn:null}
const text={
 ka:{newTitle:'სერვისის დამატება',editTitle:'სერვისის რედაქტირება',basic:'ძირითადი ინფორმაცია',short:'მოკლე აღწერა',full:'სრული აღწერა',category:'კატეგორია',type:'მომსახურების ტიპი',pricing:'ფასი და მიწოდება',packages:'პაკეტები',addPackage:'პაკეტის დამატება',removePackage:'პაკეტის წაშლა',features:'პაკეტის მახასიათებლები',included:'რა შედის მომსახურებაში',addItem:'ელემენტის დამატება',process:'სამუშაო პროცესი',addStep:'ეტაპის დამატება',faq:'ხშირად დასმული კითხვები',addFaq:'კითხვის დამატება',media:'მედია',main:'მთავარი მედია',seo:'SEO',visibility:'ხილვადობა და განთავსება',featured:'რჩეული სერვისი',featuredHelp:'აჩვენე მთავარ გვერდზე რჩეულ მომსახურებებში.',popular:'პოპულარული სერვისი',popularHelp:'აჩვენე მთავარ გვერდზე პოპულარულ მომსახურებებში.',draft:'მონახაზის შენახვა',publish:'გამოქვეყნება',save:'ცვლილებების შენახვა',complete:'სერვისის სრულყოფილება',preview:'გადახედვა',slugWarn:'ბმულის შეცვლამ შეიძლება ძველი ბმულები გააუქმოს',saved:'შენახული ცვლილებები',dirty:'შეუნახავი ცვლილებები გაქვს',notFound:'სერვისი ვერ მოიძებნა',failed:'შენახვა ვერ მოხერხდა',back:'სერვისებზე დაბრუნება',uploadFirst:'მედიის ასატვირთად ჯერ შეინახეთ მონახაზი.',addFeature:'მახასიათებლის დამატება',question:'კითხვა',answer:'პასუხი',title:'სათაური',description:'აღწერა',delivery:'მიწოდების დღეები',revisions:'შესწორებები',price:'ფასი',remove:'წაშლა',one:'ერთჯერადი მომსახურება',monthly:'ყოველთვიური მომსახურება',consult:'კონსულტაცია'},
 en:{newTitle:'Add Service',editTitle:'Edit Service',basic:'Basic Information',short:'Short Description',full:'Full Description',category:'Category',type:'Service Type',pricing:'Price & Delivery',packages:'Packages',addPackage:'Add Package',removePackage:'Remove Package',features:'Package Features',included:"What's Included",addItem:'Add Item',process:'Work Process',addStep:'Add Step',faq:'Frequently Asked Questions',addFaq:'Add Question',media:'Media',main:'Main Media',seo:'SEO',visibility:'Visibility & Placement',featured:'Featured Service',featuredHelp:'Show in Featured Services on the Homepage.',popular:'Popular Service',popularHelp:'Show in Popular Services on the Homepage.',draft:'Save Draft',publish:'Publish',save:'Save Changes',complete:'Service completeness',preview:'Preview',slugWarn:'Changing the slug may break existing links',saved:'Changes saved',dirty:'You have unsaved changes',notFound:'Service not found',failed:'Unable to save changes',back:'Back to Services',uploadFirst:'Save the draft before uploading media.',addFeature:'Add Feature',question:'Question',answer:'Answer',title:'Title',description:'Description',delivery:'Delivery days',revisions:'Revisions',price:'Price',remove:'Remove',one:'One-time Service',monthly:'Monthly Service',consult:'Consultation'}
} as const
const statusNames:Record<Locale,Record<ServiceStatus,string>>={ka:{DRAFT:'მონახაზი',PENDING_REVIEW:'განხილვის მოლოდინში',ACTIVE:'აქტიური',ARCHIVED:'არქივში'},en:{DRAFT:'Draft',PENDING_REVIEW:'Pending review',ACTIVE:'Active',ARCHIVED:'Archived'}}
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const move=<T,>(items:T[],index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=items.length)return items;const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next}

export function AdminServiceEditor({locale,serviceId}:{locale:Locale;serviceId?:string}){
 const c=text[locale],isNew=!serviceId,[draft,setDraft]=useState<ServicePayload>(initial),[slug,setSlug]=useState(''),[slugTouched,setSlugTouched]=useState(false),[media,setMedia]=useState<ServiceMedia[]>([]),[savedId,setSavedId]=useState(serviceId??''),[loading,setLoading]=useState(!isNew),[notFound,setNotFound]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[uploadErrors,setUploadErrors]=useState<string[]>([])
 useEffect(()=>{if(!serviceId)return;adminApi.service(serviceId).then(value=>{const {media:items,...record}=value;setDraft({titleKa:record.titleKa,titleEn:record.titleEn,descriptionKa:record.descriptionKa,descriptionEn:record.descriptionEn,fullDescriptionKa:record.fullDescriptionKa??'',fullDescriptionEn:record.fullDescriptionEn??'',category:record.category,serviceType:record.serviceType??'ONE_TIME',priceMinor:record.priceMinor,deliveryDays:record.deliveryDays,status:record.status,isFeatured:record.isFeatured,isPopular:record.isPopular,packages:normalizeServicePackages(record.packages,record.priceMinor,record.deliveryDays),includedItems:Array.isArray(record.includedItems)?record.includedItems:[],processSteps:Array.isArray(record.processSteps)?record.processSteps:[],faqs:Array.isArray(record.faqs)?record.faqs:[],seoTitleKa:record.seoTitleKa,seoTitleEn:record.seoTitleEn,seoDescriptionKa:record.seoDescriptionKa,seoDescriptionEn:record.seoDescriptionEn});setSlug(record.slug??'');setMedia(items)}).catch(()=>setNotFound(true)).finally(()=>setLoading(false))},[serviceId])
 useEffect(()=>{const listener=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=true}};addEventListener('beforeunload',listener);return()=>removeEventListener('beforeunload',listener)},[dirty])
 const update=<K extends keyof ServicePayload>(key:K,value:ServicePayload[K])=>{setDraft(old=>({...old,[key]:value}));setDirty(true)}
 const completeness=useMemo(()=>{const checks=[draft.titleKa,draft.titleEn,draft.descriptionKa,draft.descriptionEn,draft.fullDescriptionKa,draft.fullDescriptionEn,draft.category,draft.serviceType,draft.packages.length&&draft.packages.every(x=>x.nameKa&&x.nameEn),media.some(x=>x.isPrimary),draft.includedItems.length,draft.processSteps.length];return Math.round(checks.filter(Boolean).length/checks.length*100)},[draft,media])
 const save=async(status?:ServiceStatus)=>{setBusy(true);setError('');try{const payload={...draft,status:status??draft.status};if(payload.status==='ACTIVE'&&!payload.packages.length){setError(locale==='ka'?'აქტიურ სერვისს მინიმუმ ერთი პაკეტი სჭირდება.':'An active service requires at least one package.');return}if(isNew&&!savedId){const created=await adminApi.createService({...payload,slug,source:'DIGITAL_STEP'});setSavedId(created.serviceId);history.replaceState(null,'',localePath(locale,`/admin/services/${created.serviceId}/edit`))}else await adminApi.updateService(savedId,payload);setDraft(payload);setDirty(false);setNotice(c.saved)}catch{setError(c.failed)}finally{setBusy(false)}}
 const upload=async(files:FileList|null)=>{if(!files?.length)return;if(!savedId){setError(c.uploadFirst);return}const failed:string[]=[];for(const file of Array.from(files)){try{const item=await uploadServiceMedia(savedId,file);setMedia(old=>[...old,item])}catch{failed.push(file.name)}}setUploadErrors(failed)}
 if(loading)return <div className="admin-editor-state" aria-busy="true">{locale==='ka'?'იტვირთება…':'Loading…'}</div>
 if(notFound)return <div className="admin-editor-state"><h1>{c.notFound}</h1><a href={localePath(locale,'/admin/services')}>{c.back}</a></div>
 const packageUpdate=(index:number,value:ServicePackage)=>update('packages',draft.packages.map((item,i)=>i===index?value:item))
 return <form className="service-editor" onSubmit={(event:FormEvent)=>{event.preventDefault();void save()}}><header className="service-editor-header"><div><a href={localePath(locale,'/admin/services')}>← {c.back}</a><h1>{isNew&&!savedId?c.newTitle:c.editTitle}</h1><p>{dirty?c.dirty:notice}</p></div></header>{error&&<p className="editor-error" role="alert">{error}</p>}<div className="service-editor-layout"><main>
  <Section title={c.basic}><div className="editor-grid"><Field label="Slug"><input required readOnly={!isNew||Boolean(savedId)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={e=>{setSlug(e.target.value.toLowerCase());setSlugTouched(true);setDirty(true)}}/><small>{c.slugWarn}</small></Field><Field label={c.category}><select value={draft.category} onChange={e=>update('category',e.target.value)}>{categories.map(x=><option key={x.id} value={x.id}>{x.name[locale]}</option>)}</select></Field><Field label={`${c.title} — KA`}><input required maxLength={160} value={draft.titleKa} onChange={e=>update('titleKa',e.target.value)}/></Field><Field label={`${c.title} — EN`}><input required maxLength={160} value={draft.titleEn} onChange={e=>{update('titleEn',e.target.value);if(isNew&&!slugTouched)setSlug(slugify(e.target.value))}}/></Field><Field label={`${c.short} — KA`}><textarea required maxLength={600} value={draft.descriptionKa} onChange={e=>update('descriptionKa',e.target.value)}/></Field><Field label={`${c.short} — EN`}><textarea required maxLength={600} value={draft.descriptionEn} onChange={e=>update('descriptionEn',e.target.value)}/></Field><Field label={`${c.full} — KA`}><textarea className="large" maxLength={10000} value={draft.fullDescriptionKa} onChange={e=>update('fullDescriptionKa',e.target.value)}/></Field><Field label={`${c.full} — EN`}><textarea className="large" maxLength={10000} value={draft.fullDescriptionEn} onChange={e=>update('fullDescriptionEn',e.target.value)}/></Field></div></Section>
  <Section title={c.pricing}><div className="editor-grid thirds"><Field label={c.type}><select value={draft.serviceType} onChange={e=>update('serviceType',e.target.value as ServiceType)}><option value="ONE_TIME">{c.one}</option><option value="MONTHLY">{c.monthly}</option><option value="CONSULTATION">{c.consult}</option></select></Field><Field label={`${c.price} (GEL)`}><input type="number" min="0" step="0.01" value={draft.priceMinor/100} onChange={e=>update('priceMinor',Math.round(Number(e.target.value)*100))}/></Field><Field label={c.delivery}><input type="number" min="1" max="365" value={draft.deliveryDays} onChange={e=>update('deliveryDays',Number(e.target.value))}/></Field></div></Section>
  <Section title={c.packages} action={<button type="button" onClick={()=>update('packages',[...draft.packages,blankPackage()])}>+ {c.addPackage}</button>}>{!draft.packages.length&&<EmptyState text={locale==='ka'?'ამ სერვისს ჯერ პაკეტები არ აქვს.':'This service has no packages yet.'}/>} {draft.packages.map((pack,index)=><article className="editor-item" key={pack.key}><ItemHead index={index} count={draft.packages.length} onMove={d=>update('packages',move(draft.packages,index,d))} onRemove={()=>update('packages',draft.packages.filter((_,i)=>i!==index))} remove={c.removePackage}/><div className="editor-grid thirds"><Field label="Key"><input value={pack.key} readOnly={!isNew&&!pack.key.startsWith('package-')} onChange={e=>packageUpdate(index,{...pack,key:slugify(e.target.value)})}/></Field><Field label={`${c.title} KA`}><input required value={pack.nameKa} onChange={e=>packageUpdate(index,{...pack,nameKa:e.target.value})}/></Field><Field label={`${c.title} EN`}><input required value={pack.nameEn} onChange={e=>packageUpdate(index,{...pack,nameEn:e.target.value})}/></Field><Field label={`${c.description} KA`}><textarea value={pack.descriptionKa} onChange={e=>packageUpdate(index,{...pack,descriptionKa:e.target.value})}/></Field><Field label={`${c.description} EN`}><textarea value={pack.descriptionEn} onChange={e=>packageUpdate(index,{...pack,descriptionEn:e.target.value})}/></Field><Field label={c.price}><input type="number" min="0" step=".01" value={pack.priceMinor/100} onChange={e=>packageUpdate(index,{...pack,priceMinor:Math.round(Number(e.target.value)*100)})}/></Field><Field label={c.delivery}><input type="number" min="1" value={pack.deliveryDays} onChange={e=>packageUpdate(index,{...pack,deliveryDays:Number(e.target.value)})}/></Field><Field label={c.revisions}><input type="number" min="0" value={pack.revisions} onChange={e=>packageUpdate(index,{...pack,revisions:Number(e.target.value)})}/></Field></div><h4>{c.features}</h4>{pack.features.map((feature,fi)=><div className="localized-row" key={feature.id}><input placeholder="KA" value={feature.textKa} onChange={e=>packageUpdate(index,{...pack,features:pack.features.map((x,i)=>i===fi?{...x,textKa:e.target.value}:x)})}/><input placeholder="EN" value={feature.textEn} onChange={e=>packageUpdate(index,{...pack,features:pack.features.map((x,i)=>i===fi?{...x,textEn:e.target.value}:x)})}/><button type="button" onClick={()=>packageUpdate(index,{...pack,features:pack.features.filter((_,i)=>i!==fi)})}>×</button></div>)}<button type="button" onClick={()=>packageUpdate(index,{...pack,features:[...pack.features,{id:uid(),textKa:'',textEn:''}]})}>+ {c.addFeature}</button></article>)}</Section>
  <Section title={c.included} action={<button type="button" onClick={()=>update('includedItems',[...draft.includedItems,{id:uid(),textKa:'',textEn:''}])}>+ {c.addItem}</button>}>{!draft.includedItems.length&&<EmptyState text={locale==='ka'?'ჯერ არცერთი ელემენტი არ არის დამატებული.':'No included items yet.'}/>}<LocalizedRows items={draft.includedItems} update={items=>update('includedItems',items)}/></Section>
  <Section title={c.process} action={<button type="button" onClick={()=>update('processSteps',[...draft.processSteps,{id:uid(),titleKa:'',titleEn:'',textKa:'',textEn:''}])}>+ {c.addStep}</button>}>{!draft.processSteps.length&&<EmptyState text={locale==='ka'?'სამუშაო ეტაპები ჯერ არ არის დამატებული.':'No process steps yet.'}/>} {draft.processSteps.map((step,index)=><article className="editor-item" key={step.id}><ItemHead index={index} count={draft.processSteps.length} onMove={d=>update('processSteps',move(draft.processSteps,index,d))} onRemove={()=>update('processSteps',draft.processSteps.filter((_,i)=>i!==index))} remove={c.remove}/><div className="editor-grid">{(['titleKa','titleEn','textKa','textEn'] as const).map(key=><Field key={key} label={`${key.startsWith('title')?c.title:c.description} ${key.endsWith('Ka')?'KA':'EN'}`}><input value={step[key]} onChange={e=>update('processSteps',draft.processSteps.map((x,i)=>i===index?{...x,[key]:e.target.value}:x))}/></Field>)}</div></article>)}</Section>
  <Section title={c.faq} action={<button type="button" onClick={()=>update('faqs',[...draft.faqs,{id:uid(),questionKa:'',questionEn:'',answerKa:'',answerEn:''}])}>+ {c.addFaq}</button>}>{!draft.faqs.length&&<EmptyState text={locale==='ka'?'კითხვები ჯერ არ არის დამატებული.':'No FAQs yet.'}/>} {draft.faqs.map((faq,index)=><article className="editor-item" key={faq.id}><ItemHead index={index} count={draft.faqs.length} onMove={d=>update('faqs',move(draft.faqs,index,d))} onRemove={()=>update('faqs',draft.faqs.filter((_,i)=>i!==index))} remove={c.remove}/><div className="editor-grid">{(['questionKa','questionEn','answerKa','answerEn'] as const).map(key=><Field key={key} label={`${key.startsWith('question')?c.question:c.answer} ${key.endsWith('Ka')?'KA':'EN'}`}><textarea value={faq[key]} onChange={e=>update('faqs',draft.faqs.map((x,i)=>i===index?{...x,[key]:e.target.value}:x))}/></Field>)}</div></article>)}</Section>
  <Section title={c.media}><p>{savedId?'10 images / 3 videos.':c.uploadFirst}</p>{!media.length&&<EmptyState text={locale==='ka'?'მედია ჯერ არ არის ატვირთული.':'No media uploaded yet.'}/>}<div className="editor-media-grid">{media.map((item,index)=><article key={item.id}>{item.type==='IMAGE'?<img src={item.url} alt=""/>:<video src={item.url} controls preload="metadata"/>}<span>{item.type}</span>{item.isPrimary&&<strong>{c.main}</strong>}<div>{!item.isPrimary&&<button type="button" onClick={async()=>{await adminApi.setPrimaryMedia(savedId,item.id);setMedia(old=>old.map(x=>({...x,isPrimary:x.id===item.id})))}}>{c.main}</button>}<button type="button" disabled={!index} onClick={async()=>{const next=move(media,index,-1);setMedia(next);await adminApi.reorderMedia(savedId,next.map(x=>x.id))}}>←</button><button type="button" disabled={index===media.length-1} onClick={async()=>{const next=move(media,index,1);setMedia(next);await adminApi.reorderMedia(savedId,next.map(x=>x.id))}}>→</button><button type="button" onClick={async()=>{await deleteServiceMedia(savedId,item.id);setMedia(old=>old.filter(x=>x.id!==item.id))}}>×</button></div></article>)}</div><div className="editor-grid"><label className="upload-zone"><span aria-hidden="true">▧</span><strong>{locale==='ka'?'სურათების ატვირთვა':'Upload images'}</strong><small>PNG, JPG, WEBP, AVIF</small><input disabled={!savedId} type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>void upload(e.target.files)}/></label><label className="upload-zone"><span aria-hidden="true">▶</span><strong>{locale==='ka'?'ვიდეოს ატვირთვა':'Upload video'}</strong><small>MP4, WEBM, MOV</small><input disabled={!savedId} type="file" multiple accept="video/mp4,video/webm,video/quicktime" onChange={e=>void upload(e.target.files)}/></label></div>{uploadErrors.length>0&&<p role="alert">{uploadErrors.join(', ')}</p>}</Section>
  <Section title={c.seo}><div className="editor-grid">{(['seoTitleKa','seoTitleEn','seoDescriptionKa','seoDescriptionEn'] as const).map(key=><Field key={key} label={key.replace('seo','SEO ')}><textarea value={draft[key]??''} onChange={e=>update(key,e.target.value||null)}/></Field>)}</div></Section>
 </main><aside className="service-editor-sidebar"><Section title={c.visibility}><Field label="Status"><select value={draft.status} onChange={e=>update('status',e.target.value as ServiceStatus)}>{(['DRAFT','PENDING_REVIEW','ACTIVE','ARCHIVED'] as ServiceStatus[]).map(x=><option key={x} value={x}>{statusNames[locale][x]}</option>)}</select></Field><label className="placement-switch"><input type="checkbox" checked={draft.isFeatured} onChange={e=>update('isFeatured',e.target.checked)}/><span><strong>{c.featured}</strong><small>{c.featuredHelp}</small></span></label><label className="placement-switch"><input type="checkbox" checked={draft.isPopular} onChange={e=>update('isPopular',e.target.checked)}/><span><strong>{c.popular}</strong><small>{c.popularHelp}</small></span></label></Section><Section title={c.preview}><div className="editor-preview">{media.find(x=>x.isPrimary)?.type==='IMAGE'?<img src={media.find(x=>x.isPrimary)?.url} alt=""/>:<div className="preview-fallback">Digital Step</div>}<span>Digital Step</span><h3>{draft[locale==='ka'?'titleKa':'titleEn']||c.title}</h3><strong>{(draft.priceMinor/100).toFixed(2)} GEL</strong><div>{draft.isFeatured&&`★ ${c.featured}`} {draft.isPopular&&`↗ ${c.popular}`}</div></div><p>{draft.packages.length} {c.packages} · {draft.includedItems.length} {c.included} · {draft.processSteps.length} {c.process} · {draft.faqs.length} FAQ</p><label>{c.complete}: {completeness}%<progress max="100" value={completeness}/></label></Section><div className="editor-save-actions">{isNew&&!savedId?<><button type="button" disabled={busy} onClick={()=>void save('DRAFT')}>{c.draft}</button><button className="admin-primary" type="button" disabled={busy} onClick={()=>void save('ACTIVE')}>{c.publish}</button></>:<button className="admin-primary" disabled={busy}>{c.save}</button>}</div></aside></div></form>
}
function EmptyState({text}:{text:string}){return <div className="editor-empty"><span>＋</span><p>{text}</p></div>}
function Section({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="editor-section"><header><h2>{title}</h2>{action}</header>{children}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>}
function ItemHead({index,count,onMove,onRemove,remove}:{index:number;count:number;onMove:(d:-1|1)=>void;onRemove:()=>void;remove:string}){return <header><strong>#{index+1}</strong><div><button type="button" disabled={!index} onClick={()=>onMove(-1)}>↑</button><button type="button" disabled={index===count-1} onClick={()=>onMove(1)}>↓</button><button type="button" onClick={onRemove}>{remove}</button></div></header>}
function LocalizedRows({items,update}:{items:ServicePayload['includedItems'];update:(items:ServicePayload['includedItems'])=>void}){return <>{items.map((item,index)=><div className="localized-row" key={item.id}><input placeholder="KA" value={item.textKa} onChange={e=>update(items.map((x,i)=>i===index?{...x,textKa:e.target.value}:x))}/><input placeholder="EN" value={item.textEn} onChange={e=>update(items.map((x,i)=>i===index?{...x,textEn:e.target.value}:x))}/><button type="button" disabled={!index} onClick={()=>update(move(items,index,-1))}>↑</button><button type="button" disabled={index===items.length-1} onClick={()=>update(move(items,index,1))}>↓</button><button type="button" onClick={()=>update(items.filter((_,i)=>i!==index))}>×</button></div>)}</>}
