import { useState,type FormEvent } from 'react'
import { ArrowLeft,Check } from 'lucide-react'
import { findOrderService } from '../../../shared/orderCatalog'
import { useAuth } from '../../auth/AuthContext'
import { localePath,type Locale } from '../../i18n'
import { OrderApiError,ordersApi } from '../../lib/api/orders'
import { formatPriceMinor } from '../dashboard/dashboardUtils'
const copy={ka:{title:'შეკვეთის გაფორმება',summary:'შეკვეთის შეჯამება',details:'პროექტის დეტალები',describe:'აღწერე, რა გჭირდება',requirements:'მოთხოვნები',reference:'საცნობარო ბმული',create:'შეკვეთის შექმნა',creating:'შეკვეთა იქმნება...',service:'მომსახურება',provider:'მიმწოდებელი',package:'პაკეტი',delivery:'მიწოდების სავარაუდო ვადა',days:'დღე',subtotal:'ქვეჯამი',total:'ჯამი',payment:'გადახდა',paymentNote:'გადახდა შემდეგ ეტაპზე დაემატება',serviceMissing:'მომსახურება ვერ მოიძებნა',packageMissing:'პაკეტი ვერ მოიძებნა',back:'მარკეტპლეისის ნახვა',required:'აღწერე პროექტი მინიმუმ 10 სიმბოლოთი',url:'შეიყვანე სწორი ბმული',failed:'შეკვეთის შექმნა ვერ მოხერხდა'},en:{title:'Review Order',summary:'Order Summary',details:'Project Details',describe:'Describe what you need',requirements:'Requirements',reference:'Reference Link',create:'Create Order',creating:'Creating order...',service:'Service',provider:'Provider',package:'Package',delivery:'Estimated Delivery',days:'days',subtotal:'Subtotal',total:'Total',payment:'Payment',paymentNote:'Payment will be added in a later stage',serviceMissing:'Service not found',packageMissing:'Package not found',back:'Browse Marketplace',required:'Describe the project in at least 10 characters',url:'Enter a valid URL',failed:'Unable to create order'}} as const
export function CheckoutPage({locale}:{locale:Locale}){const c=copy[locale],{user,loading}=useAuth(),params=new URLSearchParams(window.location.search),service=findOrderService(params.get('service')??''),pack=service?.packages.find(p=>p.id===params.get('package'));const [requirements,setRequirements]=useState(''),[links,setLinks]=useState(['','']),[error,setError]=useState(''),[busy,setBusy]=useState(false);if(!loading&&!user){const returnTo=window.location.pathname+window.location.search;window.location.assign(localePath(locale,`/login?returnTo=${encodeURIComponent(returnTo)}`));return null}if(!service||!pack)return <div className="not-found"><h1>{service?c.packageMissing:c.serviceMissing}</h1><a href={localePath(locale,'/marketplace')}><ArrowLeft/>{c.back}</a></div>;async function submit(e:FormEvent){e.preventDefault();if(busy)return;if(requirements.trim().length<10){setError(c.required);return}const refs=links.filter(Boolean);if(refs.some(x=>{try{new URL(x);return false}catch{return true}})){setError(c.url);return}setBusy(true);setError('');try{const {order}=await ordersApi.create({serviceSlug:service!.slug,packageId:pack!.id,requirements:requirements.trim(),referenceLinks:refs});window.location.assign(localePath(locale,`/dashboard/orders/${order.id}?created=1`))}catch(e){setError(e instanceof OrderApiError&&e.code==='UNAUTHENTICATED'?c.failed:c.failed);setBusy(false)}}return <div className="checkout-page"><header><h1>{c.title}</h1><p>{service.title[locale]} · {service.providerName}</p></header><form className="checkout-grid" onSubmit={submit} noValidate><section className="checkout-form detail-panel"><h2>{c.details}</h2><p>{c.describe}</p><label htmlFor="requirements">{c.requirements}</label><textarea id="requirements" value={requirements} maxLength={5000} rows={9} onChange={e=>setRequirements(e.target.value)} aria-invalid={Boolean(error)} aria-describedby={error?'checkout-error':undefined}/>{links.map((link,i)=><label key={i}>{c.reference} {i+1}<input type="url" value={link} maxLength={1000} onChange={e=>setLinks(x=>x.map((v,j)=>j===i?e.target.value:v))}/></label>)}{error&&<p id="checkout-error" className="field-error">{error}</p>}</section><aside className="checkout-summary detail-panel"><h2>{c.summary}</h2><dl><div><dt>{c.service}</dt><dd>{service.title[locale]}</dd></div><div><dt>{c.provider}</dt><dd>{service.providerName}</dd></div><div><dt>{c.package}</dt><dd>{pack.name[locale]}</dd></div><div><dt>{c.delivery}</dt><dd>{pack.deliveryDays} {c.days}</dd></div></dl><ul>{pack.features.map(f=><li key={f.en}><Check/>{f[locale]}</li>)}</ul><p>{c.subtotal}<strong>{formatPriceMinor(pack.priceMinor)}</strong></p><p>{c.payment}<small>{c.paymentNote}</small></p><p className="checkout-total">{c.total}<strong>{formatPriceMinor(pack.priceMinor)}</strong></p><button className="auth-primary" disabled={busy} aria-busy={busy}>{busy?c.creating:c.create}</button></aside></form></div>}
