/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from 'react'
import { ArrowLeft, MessageCircle, Paperclip, Search, Send } from 'lucide-react'
import { useAuth } from '../../auth/AuthContext'
import { localePath, type Locale } from '../../i18n'
import { MessageApiError, messagesApi, type ChatMessage, type ConversationDetail, type ConversationSummary } from '../../lib/api/messages'

const copy={
 ka:{title:'შეტყობინებები',conversations:'საუბრები',search:'საუბრის ძიება...',all:'ყველა',unread:'ახალი',select:'აირჩიე საუბარი',selectText:'სიიდან აირჩიე საუბარი შეტყობინებების სანახავად',write:'შეტყობინების დაწერა',send:'გაგზავნა',order:'შეკვეთის ნახვა',today:'დღეს',yesterday:'გუშინ',empty:'ჯერ შეტყობინებები არ გაქვს.',browse:'შეკვეთების ნახვა',back:'უკან',attachments:'მიმაგრებული ფაილები მალე დაემატება',notFound:'საუბარი ვერ მოიძებნა',noResults:'საუბარი ვერ მოიძებნა',unreadLabel:'{count} ახალი შეტყობინება',loadError:'საუბრები ვერ ჩაიტვირთა',sendError:'შეტყობინების გაგზავნა ვერ მოხერხდა',retry:'სცადე ხელახლა',package:'პაკეტი',status:'სტატუსი',loading:'იტვირთება…'},
 en:{title:'Messages',conversations:'Conversations',search:'Search conversations...',all:'All',unread:'New',select:'Select a conversation',selectText:'Choose a conversation from the list to view messages',write:'Write a message',send:'Send',order:'View Order',today:'Today',yesterday:'Yesterday',empty:"You don't have any messages yet.",browse:'View Orders',back:'Back',attachments:'Attachments are coming soon',notFound:'Conversation not found',noResults:'No conversations found',unreadLabel:'{count} new messages',loadError:'Unable to load conversations',sendError:'Unable to send message',retry:'Try Again',package:'Package',status:'Status',loading:'Loading…'},
} as const
const initials=(name:string)=>name.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()
const localeCode=(locale:Locale)=>locale==='ka'?'ka-GE':'en-US'
const time=(iso:string,locale:Locale)=>new Intl.DateTimeFormat(localeCode(locale),{hour:'2-digit',minute:'2-digit'}).format(new Date(iso))
const dayKey=(iso:string)=>new Date(iso).toDateString()
function dateLabel(iso:string,locale:Locale){const date=new Date(iso),today=new Date(),yesterday=new Date();yesterday.setDate(today.getDate()-1);if(dayKey(iso)===today.toDateString())return copy[locale].today;if(date.toDateString()===yesterday.toDateString())return copy[locale].yesterday;return new Intl.DateTimeFormat(localeCode(locale),{dateStyle:'medium'}).format(date)}
function Avatar({name}:{name:string}){return <span className="message-avatar" aria-hidden="true">{initials(name)}</span>}

function ConversationList({locale,items,selectedId,loading,error,reload}:{locale:Locale;items:ConversationSummary[];selectedId?:string;loading:boolean;error:string;reload:()=>void}){
 const c=copy[locale],[query,setQuery]=useState(''),[onlyUnread,setOnlyUnread]=useState(false)
 const shown=useMemo(()=>items.filter(item=>{const haystack=`${item.participant.displayName} ${item.serviceTitle[locale]} ${item.orderNumber}`.toLocaleLowerCase(localeCode(locale));return haystack.includes(query.trim().toLocaleLowerCase(localeCode(locale)))&&(!onlyUnread||item.unreadCount>0)}),[items,locale,onlyUnread,query])
 return <section className="conversation-list-panel" aria-labelledby="conversation-heading"><header><h2 id="conversation-heading">{c.conversations}</h2><span>{items.length}</span></header><label className="conversation-search"><span className="visually-hidden">{c.search}</span><Search aria-hidden="true"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search}/></label><div className="conversation-filters" role="group" aria-label={c.conversations}><button type="button" aria-pressed={!onlyUnread} onClick={()=>setOnlyUnread(false)}>{c.all}</button><button type="button" aria-pressed={onlyUnread} onClick={()=>setOnlyUnread(true)}>{c.unread}</button></div>{loading?<div className="conversation-list-empty"><p>{c.loading}</p></div>:error?<div className="conversation-list-empty" role="alert"><p>{error}</p><button type="button" onClick={reload}>{c.retry}</button></div>:shown.length?<ul className="conversation-list">{shown.map(item=><li key={item.id}><a className={`conversation-item ${item.unreadCount?'unread':''}`} href={localePath(locale,`${window.location.pathname.includes('/provider/')?'/provider/messages':'/dashboard/messages'}/${item.id}`)} aria-current={item.id===selectedId?'page':undefined}><Avatar name={item.participant.displayName}/><span className="conversation-copy"><span className="conversation-top"><strong>{item.participant.displayName}</strong><time dateTime={item.lastMessageAt}>{time(item.lastMessageAt,locale)}</time></span><small>{item.serviceTitle[locale]} · #{item.orderNumber}</small><span className="conversation-preview">{item.lastMessage}</span></span>{item.unreadCount>0&&<span className="unread-badge" aria-label={c.unreadLabel.replace('{count}',String(item.unreadCount))}>{item.unreadCount}</span>}</a></li>)}</ul>:<div className="conversation-list-empty"><MessageCircle/><p>{query||onlyUnread?c.noResults:c.empty}</p>{!query&&!onlyUnread&&<a href={localePath(locale,window.location.pathname.includes('/provider/')?'/provider/orders':'/dashboard/orders')}>{c.browse}</a>}</div>}</section>
}

function MessageBubble({message,own,locale}:{message:ChatMessage;own:boolean;locale:Locale}){return <div className={`message-row ${own?'customer':'provider'}`}><div className="message-bubble"><p>{message.content}</p><footer><time dateTime={message.createdAt}>{time(message.createdAt,locale)}</time></footer></div></div>}
function ChatPanel({locale,conversation,onSent}:{locale:Locale;conversation:ConversationDetail;onSent:()=>void}){
 const c=copy[locale],{user}=useAuth(),[messages,setMessages]=useState(conversation.messages),[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),end=useRef<HTMLDivElement>(null),history=useRef<HTMLDivElement>(null)
 const providerView=window.location.pathname.includes('/provider/'),base=providerView?'/provider/messages':'/dashboard/messages',orderPath=providerView?`/provider/orders/${conversation.orderId}`:`/dashboard/orders/${conversation.orderId}`
 const acknowledge=async(items:ChatMessage[])=>{const messageIds=items.filter(message=>message.senderUserId!==user?.id&&!message.readAt).map(message=>message.id);if(!messageIds.length)return;try{for(let index=0;index<messageIds.length;index+=1000)await messagesApi.markConversationRead(conversation.id,messageIds.slice(index,index+1000));onSent()}catch{/* A later refresh retries unread messages that were not acknowledged. */}}
 useEffect(()=>{
  let active=true
  setMessages(conversation.messages)
  acknowledge(conversation.messages)
  requestAnimationFrame(()=>end.current?.scrollIntoView())
  const refresh=async()=>{if(document.visibilityState!=='visible')return;try{const result=await messagesApi.getConversation(conversation.id);if(!active)return;const container=history.current,nearBottom=!container||container.scrollHeight-container.scrollTop-container.clientHeight<120;setMessages(result.conversation.messages);acknowledge(result.conversation.messages);if(nearBottom)requestAnimationFrame(()=>end.current?.scrollIntoView({behavior:'smooth'}))}catch{/* Keep the current history visible during a transient polling failure. */}}
  const timer=window.setInterval(()=>void refresh(),15000)
  const visibility=()=>{if(document.visibilityState==='visible')void refresh()}
  document.addEventListener('visibilitychange',visibility)
  return()=>{active=false;window.clearInterval(timer);document.removeEventListener('visibilitychange',visibility)}
 },[conversation.id])
 async function submit(event?:FormEvent){event?.preventDefault();const content=draft.trim();if(!content||sending)return;setSending(true);setError('');try{const result=await messagesApi.sendMessage(conversation.id,content);setMessages(current=>[...current,result.message]);setDraft('');onSent();requestAnimationFrame(()=>end.current?.scrollIntoView({behavior:'smooth'}))}catch{setError(c.sendError)}finally{setSending(false)}}
 function keyDown(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void submit()}}
 return <section className="chat-panel" aria-label={`${c.conversations}: ${conversation.participant.displayName}`}><header className="chat-header"><a className="chat-back" href={localePath(locale,base)} aria-label={c.back}><ArrowLeft/></a><Avatar name={conversation.participant.displayName}/><div><strong>{conversation.participant.displayName}</strong><small>{conversation.order.serviceTitle[locale]} · #{conversation.order.orderNumber}</small></div></header><aside className="message-order-context"><div><small>#{conversation.order.orderNumber}</small><strong>{conversation.order.serviceTitle[locale]}</strong><span>{c.package}: {conversation.order.packageName[locale]} · {c.status}: {conversation.order.status.replaceAll('_',' ')}</span></div><a href={localePath(locale,orderPath)}>{c.order}</a></aside><div ref={history} className="message-history" aria-live="polite">{messages.map((message,index)=>{const previous=messages[index-1],separator=!previous||dayKey(previous.createdAt)!==dayKey(message.createdAt);return <div key={message.id}>{separator&&<div className="date-separator"><span>{dateLabel(message.createdAt,locale)}</span></div>}<MessageBubble message={message} own={message.senderUserId===user?.id} locale={locale}/></div>})}<div ref={end}/></div><form className="message-composer" onSubmit={submit}>{error&&<span className="composer-error" role="alert">{error}</span>}<label><span className="visually-hidden">{c.write}</span><textarea rows={1} maxLength={3000} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={keyDown} placeholder={c.write}/></label><button type="button" disabled title={c.attachments} aria-label={c.attachments}><Paperclip/></button><button className="composer-send" type="submit" disabled={sending||!draft.trim()} aria-label={c.send} aria-busy={sending}><Send/><span>{c.send}</span></button></form></section>
}

export function MessagesPage({locale,conversationId}:{locale:Locale;conversationId?:string}){
 const c=copy[locale],[items,setItems]=useState<ConversationSummary[]>([]),[conversation,setConversation]=useState<ConversationDetail|null>(null),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(Boolean(conversationId)),[error,setError]=useState(''),[detailError,setDetailError]=useState('')
 const loadList=()=>{setError('');setLoading(true);messagesApi.getConversations().then(x=>setItems(x.conversations)).catch(e=>{if(e instanceof MessageApiError&&e.code==='UNAUTHENTICATED')window.location.assign(localePath(locale,`/login?returnTo=${encodeURIComponent(window.location.pathname)}`));else setError(c.loadError)}).finally(()=>setLoading(false))}
 useEffect(loadList,[locale])
 useEffect(()=>{if(!conversationId){setConversation(null);setDetailLoading(false);return}setDetailLoading(true);setDetailError('');messagesApi.getConversation(conversationId).then(x=>setConversation(x.conversation)).catch(()=>setDetailError(c.notFound)).finally(()=>setDetailLoading(false))},[conversationId,locale])
 return <div className={`messages-page ${conversationId?'has-selection':''}`}><header className="messages-title"><h1>{c.title}</h1></header><div className="messaging-layout"><ConversationList locale={locale} items={items} selectedId={conversationId} loading={loading} error={error} reload={loadList}/>{detailLoading?<section className="chat-empty"><p>{c.loading}</p></section>:detailError?<section className="chat-empty"><MessageCircle/><h2>{detailError}</h2><a href={localePath(locale,window.location.pathname.includes('/provider/')?'/provider/messages':'/dashboard/messages')}>{c.back}</a></section>:conversation?<ChatPanel locale={locale} conversation={conversation} onSent={loadList}/>:<section className="chat-empty"><MessageCircle/><h2>{c.select}</h2><p>{c.selectText}</p></section>}</div></div>
}
