import { ArrowRight, CalendarDays, Check, FileText } from 'lucide-react'
import type { Order, OrderStatus } from '../../data/customer'
import { localePath, type Locale } from '../../i18n'
import { dashboardCopy, formatDate, formatPrice } from './dashboardUtils'
export function StatusBadge({status,locale}:{status:OrderStatus;locale:Locale}){return <span className={`order-status status-${status}`}><i aria-hidden="true"/>{dashboardCopy[locale].status[status]}</span>}
export function OrderCard({order,locale,compact=false}:{order:Order;locale:Locale;compact?:boolean}){const c=dashboardCopy[locale];return <article className={`order-card ${compact?'compact':''}`}><div className={`order-preview preview-${order.preview}`} aria-hidden="true"><span/><span/><span/></div><div className="order-main"><div className="order-topline"><small>{c.order} #{order.orderNumber}</small><StatusBadge status={order.status} locale={locale}/></div><h3>{order.serviceTitle[locale]}</h3><p>{c.provider}: <strong>{order.providerName}</strong></p>{!compact&&<div className="order-facts"><span>{c.created}<b>{formatDate(order.createdAt,locale)}</b></span><span>{c.package}<b>{order.packageName[locale]}</b></span></div>}<div className="order-progress"><div><span>{c.status[order.status]}</span><b>{order.progress}%</b></div><progress max="100" value={order.progress}>{order.progress}%</progress></div></div><div className="order-aside"><span><CalendarDays/>{c.delivery}<b>{formatDate(order.deliveryDate,locale)}</b></span><strong>{formatPrice(order.price)}</strong><a href={localePath(locale,`/dashboard/orders/${order.id}`)}>{c.view}<ArrowRight/></a></div></article>}
const currentIndex:Record<OrderStatus,number>={new:0,inProgress:2,inReview:3,completed:4,cancelled:0}
export function OrderTimeline({order,locale}:{order:Order;locale:Locale}){const active=currentIndex[order.status];return <ol className="order-timeline">{dashboardCopy[locale].stages.map((label,index)=><li key={label} className={index<active?'complete':index===active?'current':'future'} aria-current={index===active?'step':undefined}><span>{index<=active?<Check/>:index+1}</span><strong>{label}</strong><small>{index<active?'✓':index===active?`${order.progress}%`:'—'}</small></li>)}</ol>}
export function DashboardSkeleton({kind='stats'}:{kind?:'stats'|'orders'|'detail'|'profile'|'auth'}){return <div className={`dashboard-skeleton skeleton-${kind}`} aria-hidden="true">{Array.from({length:kind==='stats'?4:3},(_,i)=><span key={i}/>)}</div>}
export function AttachmentRow({name,type,size}:{name:string;type:string;size:string}){return <div className="attachment-row"><FileText/><span><strong>{name}</strong><small>{type} · {size}</small></span></div>}
