import { ArrowRight, CalendarDays, Check, Package } from 'lucide-react'
import type { ApiOrder, OrderStatus } from '../../lib/api/orders'
import { localePath,type Locale } from '../../i18n'
import { dashboardCopy,formatDate,formatPriceMinor } from './dashboardUtils'
export function StatusBadge({status,locale}:{status:OrderStatus;locale:Locale}){return <span className={`order-status status-${status.toLowerCase()}`}><i aria-hidden="true"/>{dashboardCopy[locale].status[status]}</span>}
export function OrderCard({order,locale,compact=false,nextAction}:{order:ApiOrder;locale:Locale;compact?:boolean;nextAction?:string}){const c=dashboardCopy[locale];return <article className={`order-card ${compact?'compact':''}`}><div className={`order-preview preview-${order.serviceId}`} aria-hidden="true"><Package/></div><div className="order-main"><div className="order-topline"><small>{c.order} #{order.orderNumber}</small><StatusBadge status={order.status} locale={locale}/></div><h3>{order.serviceTitle[locale]}</h3><p>{c.provider}: <strong>{order.providerName}</strong></p><div className="order-facts"><span>{c.package}<b>{order.packageName[locale]}</b></span>{!compact&&<span>{c.created}<b>{formatDate(order.createdAt,locale)}</b></span>}</div>{nextAction&&<p className="order-next-action">{nextAction}</p>}</div><div className="order-aside"><span><CalendarDays/>{c.delivery}<b>{formatDate(order.deliveryDate,locale)}</b></span><strong>{formatPriceMinor(order.priceMinor)}</strong><a href={localePath(locale,`/dashboard/orders/${order.id}`)}>{c.view}<ArrowRight/></a></div></article>}
const stages:OrderStatus[]=['PENDING','CONFIRMED','IN_PROGRESS','IN_REVIEW','COMPLETED']
export function OrderTimeline({order,locale}:{order:ApiOrder;locale:Locale}){if(order.status==='CANCELLED')return <div className="cancelled-timeline" role="status"><span>×</span><div><strong>{dashboardCopy[locale].status.CANCELLED}</strong><p>{locale==='ka'?'შეკვეთის პროგრესი შეჩერებულია.':'Order progress has stopped.'}</p></div></div>;const active=stages.indexOf(order.status);return <ol className="order-timeline">{dashboardCopy[locale].stages.map((label,index)=><li key={label} className={index<active?'complete':index===active?'current':'future'} aria-current={index===active?'step':undefined}><span>{index<=active?<Check/>:index+1}</span><strong>{label}</strong><small>{index<active?'✓':index===active?'●':'—'}</small></li>)}</ol>}
export function DashboardSkeleton({kind='orders'}:{kind?:string}){return <div className={`dashboard-skeleton skeleton-${kind}`} aria-label="Loading">{[1,2,3].map(i=><span key={i}/>)}</div>}
