import { useState, type FormEvent } from 'react'
import { Bell, Heart, Languages, LockKeyhole } from 'lucide-react'
import { useAuth } from '../../auth/AuthContext'
import { localePath, type Locale } from '../../i18n'
import { FormMessage } from '../auth/FormControls'

const copy={ka:{title:'პარამეტრები',sub:'მართე ანგარიშის ხელმისაწვდომი პარამეტრები',language:'ინტერფეისის ენა',languageText:'ენა ინახება ანგარიშზე და გამოიყენება შემდეგი ვიზიტისას.',save:'ენის შენახვა',saving:'ინახება...',saved:'პარამეტრები შენახულია',failed:'პარამეტრების შენახვა ვერ მოხერხდა',security:'უსაფრთხოება',password:'პაროლის შეცვლა',passwordSoon:'პაროლის შეცვლა ჯერ არ არის ხელმისაწვდომი.',notifications:'შეტყობინებების პარამეტრები',notificationsSoon:'შეტყობინებების პარამეტრები მალე დაემატება.',ka:'ქართული',en:'English'},en:{title:'Settings',sub:'Manage the account settings currently available',language:'Interface language',languageText:'Your language is saved to your account and used on future visits.',save:'Save Language',saving:'Saving...',saved:'Settings saved',failed:'Unable to save settings',security:'Security',password:'Change password',passwordSoon:'Password changes are not available yet.',notifications:'Notification preferences',notificationsSoon:'Notification preferences are coming soon.',ka:'ქართული',en:'English'}} as const

export function SettingsPage({locale}:{locale:Locale}){const c=copy[locale],{user,updateProfile}=useAuth();const [language,setLanguage]=useState<Locale>(user?.preferredLocale??locale),[busy,setBusy]=useState(false),[message,setMessage]=useState<{kind:'success'|'error';text:string}|null>(null);async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setMessage(null);try{await updateProfile({preferredLocale:language});setMessage({kind:'success',text:c.saved});if(language!==locale)window.location.assign(localePath(language,`${window.location.pathname}${window.location.search}${window.location.hash}`))}catch{setMessage({kind:'error',text:c.failed})}finally{setBusy(false)}}return <div className="dashboard-page"><header className="simple-page-heading"><h1>{c.title}</h1><p>{c.sub}</p></header><form className="settings-form" onSubmit={submit}><section className="settings-card"><header><span><Languages aria-hidden="true"/></span><div><h2>{c.language}</h2><p>{c.languageText}</p></div></header><div className="choice-row"><label><input type="radio" name="language" value="ka" checked={language==='ka'} onChange={()=>setLanguage('ka')}/><span>{c.ka}</span></label><label><input type="radio" name="language" value="en" checked={language==='en'} onChange={()=>setLanguage('en')}/><span>{c.en}</span></label></div></section><section className="settings-card muted-setting" aria-disabled="true"><header><span><LockKeyhole aria-hidden="true"/></span><div><h2>{c.security}</h2><p>{c.password}</p></div></header><FormMessage>{c.passwordSoon}</FormMessage></section><section className="settings-card muted-setting" aria-disabled="true"><header><span><Bell aria-hidden="true"/></span><div><h2>{c.notifications}</h2><p>{c.notificationsSoon}</p></div></header></section>{message&&<FormMessage kind={message.kind}>{message.text}</FormMessage>}<button className="settings-save" type="submit" disabled={busy} aria-busy={busy}>{busy?c.saving:c.save}</button></form></div>}

export function FavoritesPlaceholder({locale}:{locale:Locale}){return <div className="dashboard-empty tall"><Heart/><h1>{locale==='ka'?'რჩეულები':'Favorites'}</h1><p>{locale==='ka'?'რჩეული მომსახურებების სივრცე ჯერ არ არის ხელმისაწვდომი':'Saved services are not available yet'}</p><a href={localePath(locale,'/marketplace')}>{locale==='ka'?'მარკეტპლეისის ნახვა':'Browse Marketplace'}</a></div>}
