import { useState, type FormEvent } from 'react'
import { Bell, Heart, LockKeyhole, Monitor, UserRound } from 'lucide-react'
import type { Locale } from '../../i18n'
import { FormMessage, PasswordInput } from '../auth/FormControls'

const copy={ka:{title:'პარამეტრები',sub:'მოარგე ანგარიშის ვიზუალური პარამეტრები',account:'ანგარიში',security:'უსაფრთხოება',notifications:'შეტყობინებები',language:'ენა',appearance:'ვიზუალი',changePassword:'პაროლის შეცვლა',current:'მიმდინარე პაროლი',next:'ახალი პაროლი',confirm:'გაიმეორე ახალი პაროლი',email:'ელფოსტის შეტყობინებები',orders:'შეკვეთის განახლებები',messages:'შეტყობინებების შეტყობინებები',marketing:'მარკეტინგული შეტყობინებები',dark:'მუქი',system:'სისტემური',save:'პარამეტრების შენახვა',demo:'ცვლილებები მხოლოდ ვიზუალურია და არ შეინახება.',show:'პაროლის ჩვენება',hide:'პაროლის დამალვა'},en:{title:'Settings',sub:'Customize the visual preferences for your account',account:'Account',security:'Security',notifications:'Notifications',language:'Language',appearance:'Appearance',changePassword:'Change Password',current:'Current Password',next:'New Password',confirm:'Confirm New Password',email:'Email Notifications',orders:'Order Updates',messages:'Message Notifications',marketing:'Marketing Notifications',dark:'Dark',system:'System',save:'Save Settings',demo:'Changes are visual only and will not be persisted.',show:'Show password',hide:'Hide password'}} as const
export function SettingsPage({locale}:{locale:Locale}){const c=copy[locale];const [notices,setNotices]=useState({email:true,orders:true,messages:true,marketing:false});const [appearance,setAppearance]=useState<'dark'|'system'>('dark');const [saved,setSaved]=useState(false);function submit(e:FormEvent){e.preventDefault();setSaved(true)}return <div className="dashboard-page"><header className="simple-page-heading"><h1>{c.title}</h1><p>{c.sub}</p></header><form className="settings-form" onSubmit={submit}><section className="settings-card"><header><span><UserRound/></span><div><h2>{c.account}</h2><p>{c.language}</p></div></header><div className="choice-row"><label><input type="radio" name="language" defaultChecked={locale==='ka'}/><span>ქართული</span></label><label><input type="radio" name="language" defaultChecked={locale==='en'}/><span>English</span></label></div></section><section className="settings-card"><header><span><LockKeyhole/></span><div><h2>{c.security}</h2><p>{c.changePassword}</p></div></header><div className="settings-passwords"><PasswordInput id="current-password" label={c.current} showLabel={c.show} hideLabel={c.hide}/><PasswordInput id="new-password" label={c.next} showLabel={c.show} hideLabel={c.hide}/><PasswordInput id="confirm-new-password" label={c.confirm} showLabel={c.show} hideLabel={c.hide}/></div></section><section className="settings-card"><header><span><Bell/></span><div><h2>{c.notifications}</h2><p>{c.email}</p></div></header><div className="toggle-list">{(['email','orders','messages','marketing'] as const).map(key=><label key={key}><span>{c[key]}</span><input type="checkbox" checked={notices[key]} onChange={e=>setNotices({...notices,[key]:e.target.checked})}/></label>)}</div></section><section className="settings-card"><header><span><Monitor/></span><div><h2>{c.appearance}</h2><p>{c.dark}</p></div></header><div className="choice-row">{(['dark','system'] as const).map(key=><label key={key}><input type="radio" name="appearance" checked={appearance===key} onChange={()=>setAppearance(key)}/><span>{c[key]}</span></label>)}</div></section>{saved&&<FormMessage>{c.demo}</FormMessage>}<button className="settings-save" type="submit">{c.save}</button></form></div>}
export function MessagesPlaceholder({locale}:{locale:Locale}){return <div className="dashboard-empty tall"><Bell/><h1>{locale==='ka'?'შეტყობინებები':'Messages'}</h1><p>{locale==='ka'?'შეტყობინებების სისტემა შემდეგ ეტაპზე დაემატება':'Messaging will be added in the next stage'}</p></div>}
export function FavoritesPlaceholder({locale}:{locale:Locale}){return <div className="dashboard-empty tall"><Heart/><h1>{locale==='ka'?'რჩეულები':'Favorites'}</h1><p>{locale==='ka'?'რჩეული მომსახურებების სივრცე შემდეგ ეტაპზე დაემატება':'Saved services will be added in the next stage'}</p></div>}
