export const businessGoals=['INCREASE_SALES','ACQUIRE_CUSTOMERS','BRAND_AWARENESS','SOCIAL_MEDIA_GROWTH','ONLINE_SALES','LAUNCH_PRODUCT','AUTOMATE_PROCESSES'] as const
export const socialPlatforms=['FACEBOOK','INSTAGRAM','TIKTOK','LINKEDIN','YOUTUBE','GOOGLE','OTHER'] as const
export const brandTones=['PROFESSIONAL','FRIENDLY','PREMIUM','PLAYFUL','DIRECT','EDUCATIONAL'] as const
export const contentLanguages=['ka','en','ka-en'] as const
export type BusinessGoalValue=typeof businessGoals[number]
export type SocialPlatformValue=typeof socialPlatforms[number]
export type BrandToneValue=typeof brandTones[number]
export interface BusinessProfile {id:string;name:string;industry:string;description:string|null;website:string|null;locationMarket:string|null;productsServices:string|null;primaryOffer:string|null;targetAudience:string|null;audienceLocation:string|null;customerProblem:string|null;goals:BusinessGoalValue[];brandTone:BrandToneValue|null;brandToneNotes:string|null;preferredContentLanguage:typeof contentLanguages[number];brandValues:string|null;socialPlatforms:SocialPlatformValue[];competitors:{name:string;url?:string}[];createdAt:string;updatedAt:string}
export type BusinessProfileInput=Omit<BusinessProfile,'id'|'createdAt'|'updatedAt'>
export function businessProfileToInput(profile:BusinessProfile):BusinessProfileInput{return {name:profile.name,industry:profile.industry,description:profile.description,website:profile.website,locationMarket:profile.locationMarket,productsServices:profile.productsServices,primaryOffer:profile.primaryOffer,targetAudience:profile.targetAudience,audienceLocation:profile.audienceLocation,customerProblem:profile.customerProblem,goals:[...profile.goals],brandTone:profile.brandTone,brandToneNotes:profile.brandToneNotes,preferredContentLanguage:profile.preferredContentLanguage,brandValues:profile.brandValues,socialPlatforms:[...profile.socialPlatforms],competitors:profile.competitors.map(competitor=>({...competitor}))}}
export interface BusinessContext {businessName:string;industry:string;description:string|null;productsServices:string|null;targetAudience:string|null;goals:BusinessGoalValue[];brandTone:BrandToneValue|null;brandToneNotes:string|null;preferredContentLanguage:string;locationMarket:string|null;socialPlatforms:SocialPlatformValue[]}
export function buildBusinessContext(profile:BusinessProfile):BusinessContext{return {businessName:profile.name,industry:profile.industry,description:profile.description,productsServices:profile.productsServices,targetAudience:profile.targetAudience,goals:[...profile.goals],brandTone:profile.brandTone,brandToneNotes:profile.brandToneNotes,preferredContentLanguage:profile.preferredContentLanguage,locationMarket:profile.locationMarket,socialPlatforms:[...profile.socialPlatforms]}}
export function businessProfileCompleteness(profile:BusinessProfile){const factors=[profile.name,profile.industry,profile.description,profile.productsServices,profile.targetAudience,profile.goals.length,profile.brandTone,profile.socialPlatforms.length];return Math.round(factors.filter(Boolean).length/factors.length*100)}
