export type CatalogLocale = 'ka' | 'en'
export interface OrderCatalogPackage { id:'basic'|'standard'|'premium'; name:Record<CatalogLocale,string>; priceMinor:number; deliveryDays:number; features:Record<CatalogLocale,string>[] }
export interface OrderCatalogService { id:string; slug:string; title:Record<CatalogLocale,string>; providerName:string; providerSlug:string; packages:OrderCatalogPackage[] }
const l=(ka:string,en:string)=>({ka,en})
const features=[l('კონტენტის გეგმა','Content plan'),l('მორგებული დიზაინი','Custom design'),l('ტექსტების მომზადება','Copywriting'),l('ანგარიშგება','Reporting')]
const sources=[
 ['social-management','social-media-management','სოციალური მედიის მართვა','Social Media Management','Growth Studio',299],['business-website','business-website-development','ბიზნეს ვებსაიტის შექმნა','Business Website Development','WebCraft',799],['seo-audit','seo-audit-optimization','SEO აუდიტი და ოპტიმიზაცია','SEO Audit & Optimization','Digital Step Team',249],['brand-identity','brand-identity-design','ბრენდის იდენტობის დიზაინი','Brand Identity Design','Brand Works',449],['ad-campaign','advertising-campaign-setup','სარეკლამო კამპანიის გამართვა','Advertising Campaign Setup','Growth Studio',349],['promo-video','short-promotional-video','მოკლე სარეკლამო ვიდეო','Short Promotional Video','Motion Lab',399],['process-automation','business-process-automation','ბიზნეს პროცესების ავტომატიზაცია','Business Process Automation','Digital Step Team',599],['ai-content','ai-content-assistant','AI კონტენტის ასისტენტი','AI Content Assistant','AutomateX',219],['content-strategy','content-strategy','კონტენტის სტრატეგია','Content Strategy','Next Media',189],['email-marketing','email-marketing','ელფოსტის მარკეტინგის სისტემა','Email Marketing System','Growth Studio',279],['landing-page','landing-page','გაყიდვადი ლენდინგ გვერდი','Conversion Landing Page','WebCraft',549],['ecommerce-ui','ecommerce-ui','ონლაინ მაღაზიის UI დიზაინი','E-commerce UI Design','Pixel Lab',479],['instagram-content','instagram-content','Instagram კონტენტის პაკეტი','Instagram Content Pack','Next Media',239],['tiktok-plan','tiktok-plan','TikTok ზრდის გეგმა','TikTok Growth Plan','Growth Studio',149],['local-seo','local-seo','ლოკალური SEO გამართვა','Local SEO Setup','Digital Step Team',199],['google-ads','google-ads','Google Ads ოპტიმიზაცია','Google Ads Optimization','Next Media',329],['logo-animation','logo-animation','ლოგოს ანიმაცია','Logo Animation','Motion Lab',269],['crm-automation','crm-automation','CRM ავტომატიზაციის გამართვა','CRM Automation Setup','AutomateX',649],['ai-chat-workflow','ai-chat-workflow','AI სამუშაო პროცესის კონსულტაცია','AI Workflow Consultation','Digital Step Team',179],['growth-consulting','growth-consulting','ბიზნეს ზრდის კონსულტაცია','Business Growth Consultation','Brand Works',159],
] as const
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
export const orderCatalog:OrderCatalogService[]=sources.map(([id,slug,ka,en,provider,base])=>({id,slug,title:l(ka,en),providerName:provider,providerSlug:slugify(provider),packages:[
 {id:'basic',name:l('საბაზისო','Basic'),priceMinor:base*100,deliveryDays:7,features:features.slice(0,2)},
 {id:'standard',name:l('სტანდარტი','Standard'),priceMinor:Math.round(base*1.7)*100,deliveryDays:7,features:features.slice(0,3)},
 {id:'premium',name:l('პრემიუმი','Premium'),priceMinor:Math.round(base*2.8)*100,deliveryDays:10,features},
]}))
export const findOrderService=(slug:string)=>orderCatalog.find(service=>service.slug===slug)
