export const locales = ['ka', 'en'] as const
export type Locale = (typeof locales)[number]
export type LocalizedText = Record<Locale, string>

export const dictionary = {
  ka: {
    nav: { main: 'მთავარი', marketplace: 'მარკეტპლეისი', studio: 'Studio', business: 'ჩემი ბიზნესი', categories: 'კატეგორიები', orders: 'შეკვეთები', favorites: 'რჩეულები', messages: 'შეტყობინებები', profile: 'პროფილი', settings: 'პარამეტრები', mobile: 'მობილური ნავიგაცია', navigation: 'მთავარი ნავიგაცია' },
    shell: { search: 'მომსახურების ძიება', searchPlaceholder: 'მოძებნე მომსახურება...', filters: 'ძიების ფილტრები', cart: 'კალათა', notifications: 'შეტყობინებები', account: 'ანგარიშის მენიუ', buyer: 'მყიდველი', seller: 'გახდი გამყიდველი', sellerText: 'შესთავაზე შენი ციფრული სერვისი', start: 'დაწყება', theme: 'მუქი თემა', changeTheme: 'თემის შეცვლა', newMessage: 'ახალი შეტყობინება', language: 'English' },
    home: {
      eyebrow: 'Digital Step მარკეტპლეისი', title: 'AI და ციფრული სერვისები შენი ბიზნესის ზრდისთვის', subtitle: 'მოძებნე სერვისები და მართე ბიზნესის ზრდა ერთ სივრცეში', studioTitle:'AI სამუშაო სივრცე შენი ბიზნესისთვის', studioText:'დაგეგმე კონტენტი, მარკეტინგი და შემდეგი ნაბიჯები. რეალური AI ინტეგრაცია მზადდება.', studioCta:'Studio-ს ნახვა', browse: 'მომსახურებების ნახვა', how: 'როგორ მუშაობს', categories: 'პოპულარული კატეგორიები', allCategories: 'ყველა კატეგორია', popular: 'პოპულარული მომსახურებები', viewAll: 'ყველას ნახვა', bestsellers: 'ბესტსელერები', goalsEyebrow: 'ბიზნესის მიზნის მიხედვით', goals: 'რის მიღწევა გსურს?', works: 'როგორ მუშაობს Digital Step', services: 'მომსახურება', reviews: 'შეფასებები', from: 'დან', viewService: 'მომსახურების ნახვა', viewCategory: 'კატეგორიის ნახვა', addFavorite: 'რჩეულებში დამატება', removeFavorite: 'რჩეულებიდან წაშლა', demo: 'სადემონსტრაციო მონაცემები', loading: 'კონტენტის ჩატვირთვა', footer: 'ციფრული მომსახურებების ორგანიზებული სივრცე ბიზნესისთვის.'
    },
    badges: { popular: 'პოპულარული', bestseller: 'ბესტსელერი', new: 'ახალი', fastDelivery: 'სწრაფი მიწოდება', aiService: 'AI მომსახურება' },
    trust:{digitalStep:'Digital Step-ის სერვისი',verified:'დადასტურებული პროვაიდერი'},
    catalog: { marketplace:'მარკეტპლეისი', allServices:'ყველა მომსახურება', subtitle:'იპოვე შენთვის საჭირო ციფრული მომსახურება', servicesFound:'ნაპოვნია {count} მომსახურება', resultsFound:'ნაპოვნია {count} შედეგი', filters:'ფილტრები', clear:'ფილტრების გასუფთავება', showResults:'შედეგების ჩვენება', sort:'დალაგება', recommended:'რეკომენდებული', popular:'ყველაზე პოპულარული', rated:'მაღალი რეიტინგი', priceLow:'ფასი: დაბლიდან მაღლა', priceHigh:'ფასი: მაღლიდან დაბლა', newest:'ახლად დამატებული', category:'კატეგორია', price:'ფასი', min:'მინ.', max:'მაქს.', rating:'რეიტინგი', delivery:'მიწოდების ვადა', serviceType:'მომსახურების ტიპი', providerType:'მიმწოდებლის ტიპი', serviceProvider:'მომსახურების მიმწოდებელი', sourceDigitalStep:'Digital Step', sourceVerified:'დადასტურებული პროვაიდერები', oneTime:'ერთჯერადი მომსახურება', monthly:'ყოველთვიური მომსახურება', consultation:'კონსულტაცია', agency:'სააგენტო', specialist:'სპეციალისტი', digitalStep:'Digital Step', anyDelivery:'ნებისმიერი ვადა', dayOne:'24 საათში', dayThree:'3 დღემდე', daySeven:'7 დღემდე', grid:'ბადის ხედი', list:'სიის ხედი', noResults:'შედეგი ვერ მოიძებნა', noResultsText:'სცადე ფილტრების შეცვლა ან გასუფთავება', categoryServices:'კატეგორიის მომსახურებები', subcategories:'ქვეკატეგორიები', popularCategory:'პოპულარული ამ კატეგორიაში', allCategories:'ყველა კატეგორია', home:'მთავარი', close:'ფილტრების დახურვა', gel:'₾', viewDetails:'დეტალების ნახვა', deliveryDays:'{count} დღეში', searchTitle:'ძიების შედეგები: “{query}”', searchDemo:'სადემონსტრაციო შედეგები', related:'დაკავშირებული კატეგორიები', searchDefault:'ციფრული მომსახურება' },
  },
  en: {
    nav: { main: 'Home', marketplace: 'Marketplace', studio: 'Studio', business: 'My Business', categories: 'Categories', orders: 'Orders', favorites: 'Favorites', messages: 'Messages', profile: 'Profile', settings: 'Settings', mobile: 'Mobile navigation', navigation: 'Main navigation' },
    shell: { search: 'Search services', searchPlaceholder: 'Search for a service...', filters: 'Search filters', cart: 'Cart', notifications: 'Notifications', account: 'Account menu', buyer: 'Buyer', seller: 'Become a seller', sellerText: 'Offer your digital service', start: 'Get started', theme: 'Dark theme', changeTheme: 'Change theme', newMessage: 'New message', language: 'ქართული' },
    home: {
      eyebrow: 'Digital Step Marketplace', title: 'AI and digital services for growing your business', subtitle: 'Discover services and manage business growth in one place', studioTitle:'An AI workspace for your business', studioText:'Plan content, marketing, and next steps. Real AI integration is being prepared.', studioCta:'Explore Studio', browse: 'Browse Services', how: 'How It Works', categories: 'Popular Categories', allCategories: 'All Categories', popular: 'Popular Services', viewAll: 'View All', bestsellers: 'Bestsellers', goalsEyebrow: 'Browse by Business Goal', goals: 'What do you want to achieve?', works: 'How Digital Step Works', services: 'services', reviews: 'reviews', from: 'From', viewService: 'View Service', viewCategory: 'View Category', addFavorite: 'Add to Favorites', removeFavorite: 'Remove from Favorites', demo: 'Demo data', loading: 'Loading Content', footer: 'An organized space for business-focused digital services.'
    },
    badges: { popular: 'Popular', bestseller: 'Bestseller', new: 'New', fastDelivery: 'Fast Delivery', aiService: 'AI Service' },
    trust:{digitalStep:'Digital Step Service',verified:'Verified Provider'},
    catalog: { marketplace:'Marketplace', allServices:'All Services', subtitle:'Find the digital service you need', servicesFound:'{count} services found', resultsFound:'{count} results found', filters:'Filters', clear:'Clear Filters', showResults:'Show Results', sort:'Sort', recommended:'Recommended', popular:'Most Popular', rated:'Highest Rated', priceLow:'Price: Low to High', priceHigh:'Price: High to Low', newest:'Newest', category:'Category', price:'Price', min:'Min', max:'Max', rating:'Rating', delivery:'Delivery Time', serviceType:'Service Type', providerType:'Provider Type', serviceProvider:'Service Provider', sourceDigitalStep:'Digital Step', sourceVerified:'Verified Providers', oneTime:'One-time service', monthly:'Monthly service', consultation:'Consultation', agency:'Agency', specialist:'Specialist', digitalStep:'Digital Step', anyDelivery:'Any delivery time', dayOne:'Within 24 hours', dayThree:'Up to 3 days', daySeven:'Up to 7 days', grid:'Grid View', list:'List View', noResults:'No results found', noResultsText:'Try changing or clearing your filters', categoryServices:'Category Services', subcategories:'Subcategories', popularCategory:'Popular in this category', allCategories:'All Categories', home:'Home', close:'Close filters', gel:'GEL', viewDetails:'View details', deliveryDays:'In {count} days', searchTitle:'Search results for “{query}”', searchDemo:'Demo results', related:'Related categories', searchDefault:'digital services' },
  },
} as const

export function resolveLocale(pathname: string): Locale { return pathname.split('/')[1] === 'en' ? 'en' : 'ka' }
export function localePath(locale: Locale, destination: string): string {
  if (destination.startsWith('#')) return destination
  const [pathAndQuery, hash = ''] = destination.split('#')
  const [rawPath, query = ''] = pathAndQuery.split('?')
  const clean = `/${rawPath}`.replace(/^\/(ka|en)(?=\/|$)/, '').replace(/\/{2,}/g, '/')
  return `/${locale}${clean === '/' ? '' : clean}${query ? `?${query}` : ''}${hash ? `#${hash}` : ''}`
}
