import { BarChart3,CalendarDays,FileText,Lightbulb,LockKeyhole,Megaphone,MessageSquareText,Palette,Sparkles,Target } from 'lucide-react'
import { useAuth } from '../../auth/AuthContext'
import { canUseFeature,getUsageLimit,type StudioFeature } from '../../domain/subscriptions'
import { localePath,type Locale } from '../../i18n'
import { useBusinessProfile } from '../../hooks/useBusinessProfile'
import { buildBusinessContext,businessProfileCompleteness } from '../../../shared/businessProfile'

const copy={ka:{home:'Studio მთავარი',assistant:'AI ასისტენტი',post:'პოსტების გენერატორი',calendar:'კონტენტ კალენდარი',ideas:'კონტენტის იდეები',planner:'მარკეტინგის გეგმა',analysis:'ბიზნესის ანალიზი',analysisSections:['ბიზნესის მიმოხილვა','აუდიტორია','მიზნები','ბრენდი','ციფრული არხები'],campaign:'კამპანიის დამგეგმავი',brand:'ბრენდის სივრცე',question:'რას გავაკეთებთ დღეს?',subtitle:'შენი AI სივრცე ბიზნესის მართვისა და ზრდისთვის',available:'ხელმისაწვდომია',soon:'მალე',requires:'საჭიროა Pro გეგმა',upgrade:'განაახლე გეგმა',usage:'სადემონსტრაციო გამოყენების ლიმიტი',prepared:'AI ინტეგრაცია მზადდება. პასუხი არ გენერირებულა.',welcome:'მოგესალმებით AI ბიზნეს ასისტენტის სივრცეში',prompts:['როგორ გავზარდო გაყიდვები?','შემიდგინე კონტენტის მიმართულებები','რომელი სერვისი მჭირდება?'],context:'ბიზნესის კონტექსტი',complete:'შეავსე ბიზნეს პროფილი, რათა მომავალში Studio-მ შენი ბიზნესი გაიგოს.',send:'გაგზავნა',placeholder:'დაწერე ბიზნესის შესახებ შეკითხვა…',output:'შედეგის სივრცე',empty:'გენერირებული მასალა აქ გამოჩნდება რეალური AI ინტეგრაციის შემდეგ.',generate:'მომზადება',month:'თვე',week:'კვირა',list:'სია',profile:'ბიზნეს პროფილზე გადასვლა'},en:{home:'Studio Home',assistant:'AI Assistant',post:'Post Generator',calendar:'Content Calendar',ideas:'Content Ideas',planner:'Marketing Planner',analysis:'Business Analysis',analysisSections:['Business Overview','Audience','Goals','Brand','Digital Channels'],campaign:'Campaign Planner',brand:'Brand Workspace',question:'What are we working on today?',subtitle:'Your AI workspace for managing and growing your business',available:'Available',soon:'Coming Soon',requires:'Requires Pro',upgrade:'Upgrade Plan',usage:'Demo usage configuration',prepared:'AI integration is being prepared. No response was generated.',welcome:'Welcome to your AI Business Assistant workspace',prompts:['How can I grow sales?','Help plan my content themes','Which service do I need?'],context:'Business context',complete:'Complete your Business Profile so Studio can understand your business in the future.',send:'Send',placeholder:'Ask a question about your business…',output:'Output workspace',empty:'Generated material will appear here after a real AI integration is available.',generate:'Prepare',month:'Month',week:'Week',list:'List',profile:'Go to Business Profile'}} as const
const tools=[['assistant','AI_ASSISTANT',MessageSquareText],['post','POST_GENERATOR',FileText],['calendar','CONTENT_CALENDAR',CalendarDays],['ideas','CONTENT_IDEAS',Lightbulb],['planner','MARKETING_PLANNER',Megaphone],['analysis','BUSINESS_ANALYSIS',BarChart3],['campaign',null,Target],['brand',null,Palette]] as const
const paths={assistant:'assistant',post:'post-generator',calendar:'content-calendar',ideas:'content-ideas',planner:'marketing-planner',analysis:'business-analysis'} as const
function BusinessContextCard({locale,profile,loading}:{locale:Locale;profile:ReturnType<typeof useBusinessProfile>['profile'];loading:boolean}){if(loading)return <section className="studio-panel context-card" aria-busy="true">…</section>;if(!profile)return <section className="studio-panel context-card"><h2>{locale==='ka'?'Studio უკეთ იმუშავებს, თუ შენს ბიზნესს გავიცნობთ':'Studio works better when it understands your business'}</h2><a className="studio-button" href={localePath(locale,'/business')}>{locale==='ka'?'შეავსე ბიზნესის პროფილი':'Complete Business Profile'}</a></section>;const context=buildBusinessContext(profile);return <section className="studio-panel context-card"><h2>{context.businessName}</h2><p>{locale==='ka'?`ბიზნესის პროფილი შევსებულია ${businessProfileCompleteness(profile)}%-ით`:`Business profile is ${businessProfileCompleteness(profile)}% complete`}</p><div className="goal-summary">{context.goals.map(x=><span key={x}>{x.replaceAll('_',' ')}</span>)}<span>{context.preferredContentLanguage}</span></div></section>}
export function Usage({locale,feature='AI_ASSISTANT'}:{locale:Locale;feature?:StudioFeature}){const {user}=useAuth();if(!user)return null;const limit=getUsageLimit(user.subscriptionPlan,feature==='POST_GENERATOR'?'POST_GENERATIONS':'AI_REQUESTS');return <div className="usage"><span>{copy[locale].usage}</span><strong>0 / {limit}</strong></div>}
export function StudioLayout({locale,children}:{locale:Locale;children:ReactNode}){const c=copy[locale];return <div className="studio-page"><nav className="studio-nav" aria-label="Studio">{(['home','assistant','post','calendar','ideas','planner','analysis'] as const).map(k=><a key={k} href={localePath(locale,k==='home'?'/studio':`/studio/${paths[k]}`)}>{c[k]}</a>)}</nav>{children}</div>}
export function StudioHome({locale}:{locale:Locale}){const c=copy[locale],{user}=useAuth(),{profile,loading}=useBusinessProfile();if(!user)return null;return <><header className="studio-hero"><p><Sparkles/>Digital Step Studio</p><h1>{c.question}</h1><span>{c.subtitle}</span><b>{user.subscriptionPlan}</b></header><BusinessContextCard locale={locale} profile={profile} loading={loading}/><section className="studio-tools" aria-label="Studio tools">{tools.map(([key,feature,Icon])=>{const enabled=feature&&canUseFeature(user.subscriptionPlan,feature);const body=<><Icon/><div><h2>{c[key]}</h2><small>{feature?(enabled?c.available:c.requires):c.soon}</small></div>{feature&&!enabled&&<LockKeyhole/>}</>;return feature?<a key={key} className={!enabled?'tool-locked':''} href={localePath(locale,`/studio/${paths[key as keyof typeof paths]}`)}>{body}</a>:<article key={key}>{body}</article>})}</section></>}
export {MarketingPlannerPage,BusinessAnalysisPage} from './AnalysisToolsPages'
